### ISSUE TITLE
Limit matter server clients?

### ISSUE THREAD

**Issue by bkoblenz** [home-assistant-libs/python-matter-server#1003]
It appears that when a matter server is running, a client from anywhere can connect to that server and control matter devices on the fabric?  Is that right?

For security reasons, in my own use case, I would like to limit the matter server to client connections from localhost.  I believe I can do that easily enough in server/client_handler.py but wonder if other's might be interested in that restriction (or something similar)?

-brian

**Comment by bkoblenz** [comment]
I have an implementation for this capability.  I am not sure the process (assuming I do not have write ability to this repository) for generating a branch and a pull request.  Can someone provide guidance?

-brian

**Comment by marcelveldt** [comment]
Client from anywhere ? I may hope you didn't expose the port to the internet ?!
If you mean protect it on the local network, the common way to do so is to bind the websocket on a private interface and then make sure that your client uses the protected network/interface to talk to the device. That is something you, as a consumer of the library will have to implement.

Have a look at the Matter add-on for Home Assistant, which uses this library/server but runs the server only on the internal docker network so its not accessible from the network

**Comment by marcelveldt** [comment]
> I have an implementation for this capability. I am not sure the process (assuming I do not have write ability to this repository) for generating a branch and a pull request. Can someone provide guidance?

You fork the repo to your own personal space, create a branch and then PR against this repo.
