### ISSUE TITLE
Version compatabillity table?

### ISSUE THREAD

**Issue by 1mike12** [home-assistant-libs/python-matter-server#1015]
When the version of this container doesn't work with the version of homeassistant, the user gets a vague error of:

> The matter server is not the correct version

I think it would be great if the core project would show to the user some information on the levels it wants and the level it saw, but failing that, it would at least be nice to document what versions of this project pairs with the core project

https://github.com/home-assistant/core/issues/104927

I for example, can't use the latest core since there is something broken with a specific iot device and have to use an older version. I randomly installed like 3 releases of python-matter-server, until I realized I could look at the release dates here to find one that was close to the release date of my old HA core.  A table would've been much nicer

**Comment by marcelveldt** [comment]
Please read the description that HA related issues should be reported in the HA issue tracker.
Next to that we dont provide any support for the docker image.
