### ISSUE TITLE
Version1.0.0 will not install 

### ISSUE THREAD

**Issue by kendadk** [home-assistant-libs/python-matter-server#103]
Error  no manifest. json found

**Comment by agners** [comment]
Please be more specific what you are doing exactly. Also, is version 1.0.1 working for you?

**Comment by frenck** [comment]
@agners Considering the message, I assume it was tried to add this repository as a custom integration to Home Assistant.

**Comment by kendadk** [comment]
Deleted 0.3.0 and reinstalled 1.0.1Sent from my iPhoneOn Nov 30, 2022, at 11:26 AM, Franck Nijhof ***@***.***> wrote:﻿
@agners Considering the message, I assume it was tried to add this repository as a custom integration to Home Assistant.

**Comment by hermanops** [comment]
![Screenshot_20221130_183221_Home Assistant](https://user-images.githubusercontent.com/55062051/204867897-1e063d09-32f1-429f-bbc5-e38bb3a3fc54.png)
 
Same issue here with 1.0.1

**Comment by kendadk** [comment]
I had to uninstall 0.3.0 and reinstall 1.0.1 the addon moved from the experimental repository to the official repository. Sent from my iPhoneOn Nov 30, 2022, at 12:34 PM, hermanops ***@***.***> wrote:﻿

Same issue here with 1.0.1

**Comment by marcelveldt** [comment]
this is no longer a custom component. we should remove the hacs definition

**Comment by LordNex** [comment]
> this is no longer a custom component. we should remove the hacs definition

Getting the same error as well. Went I to HACS can when I try and get details it errors. Should I just remove it?

**Comment by marcelveldt** [comment]
Yes, please remove it from HACS and wait for next HA release, thanks!

**Comment by LordNex** [comment]
> Yes, please remove it from HACS and wait for next HA release, thanks!

I tried to uninstall the component from HACS through the drop-down and remove button, but it just spins and never removes it. Rebooting didn't help. I do have the Matter Server Official addon now running as far as I can tell but I think this is still causing a conflict with it. Any other suggestions on removing it? I am seeing the updates your pushing out but trying to update still gives the above JSON error. Thanks.
