### ISSUE TITLE
RPC and PubSub packages

### ISSUE THREAD

**Issue by jonsmirl** [home-assistant-libs/python-matter-server#11]
Would packages like these make the server easier to develop?

https://github.com/permitio/fastapi_websocket_rpc
https://github.com/permitio/fastapi_websocket_pubsub

**Comment by balloob** [comment]
The Python REPL in the Matter SDK uses their own data classes for communication. So we set up our JSON serialization to make sure we just send those objects around. I don't think that adding extra packages around it is going to make it easier since it already works 🙃
