### ISSUE TITLE
Implement Node remove/delete feature

### ISSUE THREAD

**Issue by marcelveldt** [home-assistant-libs/python-matter-server#110]
Feature to remove a node from the fabric

- [X] implement in server
- [X] implement in client
- [ ] implement in HA integration
- [ ] figure out how to reset device on the chip sdk

**Comment by MartinHjelmare** [comment]
There's only a manual remove option in the integration. Are we planning a feature for the other way around where the device in Home Assistant is removed when the device is removed from the fabric by a third party.

**Comment by marcelveldt** [comment]
1) The remove option in HA currently also sends remove command to the server.
2) We need to handle the fact that the nod eis already dead and catch the exception from the Matter stack (and just delete the node from HA and/or server).
3) We need to make sure that at startup we compare the previous nodes in device registry to delete/cleanup any removed nodes.
4) We need to handle the node deleted event from the server.

This issue was closed because it was a duplicate with:
https://github.com/orgs/home-assistant-libs/projects/1?pane=issue&itemId=16683893
