### ISSUE TITLE
Matter docs

### ISSUE THREAD

**Issue by Grey-Lancaster** [home-assistant-libs/python-matter-server#127]
So I have the new 2022.12 and Matter server 1.07
The docs in the matter server still reflect this git hub hacs thing.
Where are the new docs? (or workshop)

I had the old matter chip turning my light of and on and now I have no clue where to look.  I find Discord very difficult.  Is there a community.hassio or reddit for HA Matter?

Thanks,
Grey

**Comment by MartinHjelmare** [comment]
Here are Matter integration docs:
https://www.home-assistant.io/integrations/matter/

We'll still working on extending the documentation.

**Comment by Grey-Lancaster** [comment]
Thanks, yes I saw that before I posted.
That is not really enough information to figure out anything :) 
How do I commission a device?

![image](https://user-images.githubusercontent.com/20055899/206318673-3ab0f934-c7df-43eb-815e-3dbb030dc5b5.png)
