### ISSUE TITLE
Standalone Docker image?

### ISSUE THREAD

**Issue by karlshea** [home-assistant-libs/python-matter-server#128]
I see there's a Docker image for this server as an addon for Home Assistant OS, what are the chances of having a standalone version that could be run alongside Home Assistant in a container?

**Comment by sreichholf** [comment]
You can just go and use `homeassistant/aarch64-addon-matter-server:latest`
Configure it using the host network and with /data as persistent path inside the container.

I just did that, and it works :)

**Comment by luisiam** [comment]
I just tried the amd64 version on my NUC and it works!

**Comment by balloob** [comment]
Home Assistant won't discover it. You will need to click add integration -> matter.

**Comment by karlshea** [comment]
It looks like it's trying to save things in `/root/.matter-server` (I see chip.json), should that also be persistent?

And I assume the errors about "Could not resolve host: supervisor" / "Something went wrong contacting the API" are okay—I think that's just how Home Assistant OS manages the addons?

**Comment by rursache** [comment]
Docker run:
```sh
docker run -d \
  --name matter-server \
  --restart unless-stopped \
  --network=host \
  -e TZ=Europe/Bucharest \
  -v /home/USER/.matter/data:/data \
  -v /home/USER/.matter/root:/root/.matter_server \
  homeassistant/amd64-addon-matter-server:latest 
```

**Comment by blauret** [comment]
> Docker run:
> 
> ```shell
> docker run -d \
>   --name matter-server \
>   --restart unless-stopped \
>   --network=host \
>   -e TZ=Europe/Bucharest \
>   -v /home/USER/.matter/data:/data \
>   -v /home/USER/.matter/root:/root/.matter_server \
>   homeassistant/amd64-addon-matter-server:latest 
> ```

This is working for me. Did you get the bluetooth interface to work in the container?

**Comment by karlshea** [comment]
I just got my ESP32 device today so I'm finally able to actually test this, and I got exactly the same error.

This is my new docker-compose:

```
version: '3.8'
services:
  matter-server:
    image: homeassistant/amd64-addon-matter-server:latest
    container_name: matter-server
    network_mode: 'host'

    volumes:
      - './data:/data'
      - './root-matter_server:/root/.matter_server'

      # For Bluetooth, expose DBus socket
      - '/run/dbus:/run/dbus:ro'

    restart: unless-stopped
```

With the DBus socket exposed I was able to start the commissioning process, but both python-matter-server and the console on the ESP32 are repeating the same errors:

**python-matter-server**
```
2022-12-13 00:18:56 citywall chip.EM[63] INFO >>> [E:60387r M:119459934] (S) Msg RX from 1:0000000000000002 [EB9F] --- Type 0001:05 (IM:ReportData)
2022-12-13 00:18:56 citywall chip.DMG[63] INFO Refresh LivenessCheckTime for 35000 milliseconds with SubscriptionId = 0xf95c1437 Peer = 01:0000000000000002
2022-12-13 00:18:56 citywall chip.EM[63] INFO <<< [E:60387r M:73464016 (Ack:119459934)] (S) Msg TX to 1:0000000000000002 [EB9F] --- Type 0001:01 (IM:StatusResponse)
2022-12-13 00:18:56 citywall chip.IN[63] INFO (S) Sending msg 73464016 on secure session with LSID: 58364
2022-12-13 00:18:56 citywall chip.EM[63] INFO >>> [E:60387r M:119459935 (Ack:73464016)] (S) Msg RX from 1:0000000000000002 [EB9F] --- Type 0000:10 (SecureChannel:StandaloneAck)
```

**ESP32**
```
I (837294) chip[DMG]: Refresh subscribe timer sync after 10 seconds
I (837304) chip[EM]: <<< [E:60392i M:119459944] (S) Msg TX to 1:000000000001B669 [EB9F] --- Type 0001:05 (IM:ReportData)
I (837304) chip[IN]: (S) Sending msg 119459944 on secure session with LSID: 15928
I (837314) chip[DMG]: Refresh Subscribe Sync Timer with min 0 seconds and max 10 seconds
I (837334) chip[EM]: >>> [E:60392i M:73464021 (Ack:119459944)] (S) Msg RX from 1:000000000001B669 [EB9F] --- Type 0001:01 (IM:StatusResponse)
I (837344) chip[IM]: Received status response, status is 0x00
I (837344) chip[EM]: <<< [E:60392i M:119459945 (Ack:73464021)] (S) Msg TX to 1:000000000001B669 [EB9F] --- Type 0000:10 (SecureChannel:StandaloneAck)
I (837354) chip[IN]: (S) Sending msg 119459945 on secure session with LSID: 15928
```

No log messages from Home Assistant itself, so something is stuck.

**Comment by karlshea** [comment]
I [posted an update here](https://community.home-assistant.io/t/matter-current-state-of-affairs/502089) for anyone following this issue.

**Comment by MichelFR** [comment]
I was running it sucessfully before, but currently i get the same output as here:
https://github.com/home-assistant-libs/python-matter-server/issues/133

**Comment by MartinHjelmare** [comment]
Please don't dilute this issue referencing other issues. Each issue should be as narrow as possible in the discussion to be meaningful. If you get the same output as described in another issue you're very likely affected by that issue and not this issue.

Thanks!

**Comment by marcelveldt** [comment]
I'll repeat here what I just answered in an issue report:

The docker image is not meant to be used standalone as it is created for the Home Assistant supervisor. For example that is where the config file is provided from. It maybe works by accident today and breaks tomorrow. Best is to create a dedicated docker image to run standalone.

At this time we are really busy with the basic stuff and polishing the Matter server and integration for daily usage, focusing on the add-on as first step and we might provide a standalone container later but if you want to pick up the glove, you can look at the add-on structure to find out what's missing for the standalone container.

**Comment by karlshea** [comment]
Are you open to packaging this standalone? If so I could start taking a look at creating a Dockerfile for that.

It seems like the addon image is pretty close, it almost seems like all that's needed is to remove the Home Assistant supervisor integration and to add some environment variables for configuration.

**Comment by balloob** [comment]
We do want to eventually offer that, but we don't have the bandwidth right now. There are too many things still in flux.

**Comment by marcelveldt** [comment]
Closing this as there is a docker alternative available although primary dev focus goes to the HA integration and companion add-on. Feel free to submit any PR's to improve the docker route. Thanks!

**Comment by rursache** [comment]
@marcelveldt 
where to find the 'docker alternative'?

the current ` homeassistant/amd64-addon-matter-server` image spits this every 2-3 seconds:
```sh
[00:11:32] INFO: Successfully send discovery information to Home Assistant.
Traceback (most recent call last):
  File "/usr/local/bin/matter-server", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/matter_server/server/__main__.py", line 71, in main
    logging.basicConfig(handlers=handlers, level=args.log_level.upper())
  File "/usr/lib/python3.9/logging/__init__.py", line 2018, in basicConfig
    root.setLevel(level)
  File "/usr/lib/python3.9/logging/__init__.py", line 1417, in setLevel
    self.level = _checkLevel(level)
  File "/usr/lib/python3.9/logging/__init__.py", line 194, in _checkLevel
    raise ValueError("Unknown level: %r" % level)
ValueError: Unknown level: 'NULL'
[00:11:33] INFO: Starting Matter Server...
curl: (6) Could not resolve host: supervisor
```

**Comment by karlshea** [comment]
Building the Docker image from source with the instructions at the bottom of the main README works, and does not look for the supervisor host (I just tried it).

(@marcelveldt FYI:)

I hadn't been running the addon version of the container for awhile so I deleted the entity/device in HA and re-commissioned it from a HomeKit pairing mode PIN (on HA 2023.1.6 and matter-server tag 1.1.0) and it worked just fine (although I had to use "Commission Device"—"Add Shared Device" did NOT work).

IMHO once the server stabilizes pretty much all the maintainers would need to do is start publishing the built Docker images and it would be ready to go. The downside of running it right now is that you'll have to keep an eye on matching versions, if you build the current HEAD it won't work with the current HA release since HEAD is now a newer Matter version.

This is my docker-compose.yml (I checked this repo out into `source` because I wanted to modify the docker-compose to move the data directory):

```
version: "3.8"
services:
  matter-server:
    build:
      context: ./source
      dockerfile: Dockerfile.dev
    image: matter-server:latest
    container_name: matter-server

    # Required for mDNS to work correctly
    network_mode: host

    security_opt:
      # needed for bluetooth via dbus
      - apparmor:unconfined

    ports:
      - "5580:5580"

    volumes:
      - ./data:/data/
      - /run/dbus:/run/dbus:ro

    restart: unless-stopped
```

Mounting a volume into `/root/.matter_server` is no longer needed (at least for the non-addon version), chip.json etc are now persisted in `/data`
