### ISSUE TITLE
Matter Docs #2

### ISSUE THREAD

**Issue by Grey-Lancaster** [home-assistant-libs/python-matter-server#129]
I see you removed the HACS python link in the add-on Docs Great and fast :)

But the top Steps 1 and 2 go to a bad place.  Not the same place that works from 
https://www.home-assistant.io/integrations/matter/

![image](https://user-images.githubusercontent.com/20055899/206477472-14074f9e-67ff-4364-b732-cfd033049445.png)

**Comment by MartinHjelmare** [comment]
Thanks for the report!
