### ISSUE TITLE
How to change /data path

### ISSUE THREAD

**Issue by flatsiedatsie** [home-assistant-libs/python-matter-server#145]
I'm trying to use this project outside of home assistant, as the script mentions it should be more generally useable, which rocks.

I notice it's looking to create and read files in `/data`. The script wouldn't run until I created that directory.  I'm assuming that with Home Assistant that directory normally exists.

If there a way to set that path to some place else? I looked in the code to find where it was set, but haven't found it so far. All I found was that in theory it should save to the [home directory](https://github.com/python/cpython/blob/53d9cd95cd91f1a291a3923acb95e0e86942291a/Lib/pathlib.py#L826). Perhaps /data is baked into the Chip library?

**Comment by MartinHjelmare** [comment]
If you start the server with the `--help` flag you will see the command line options.

This is how it looks for me:

```
(python-matter-server) x$ python -m matter_server.server --help
usage: __main__.py [-h] [--vendorid VENDORID] [--fabricid FABRICID] [--storage-path STORAGE_PATH] [--port PORT] [--log-level LOG_LEVEL] [--log-file LOG_FILE]

Matter Controller Server using WebSockets.

optional arguments:
  -h, --help            show this help message and exit
  --vendorid VENDORID   Vendor ID for the Fabric, defaults to 65521
  --fabricid FABRICID   Fabric ID for the Fabric, defaults to 1
  --storage-path STORAGE_PATH
                        Storage path to keep persistent data, defaults to /home/martin/.matter_server
  --port PORT           TCP Port to run the websocket server, defaults to 5580
  --log-level LOG_LEVEL
                        Provide logging level. Example --log-level debug, default=info, possible=(critical, error, warning, info, debug)
  --log-file LOG_FILE   Log file to write to (optional).
```

**Comment by MartinHjelmare** [comment]
How are you running the server?

**Comment by agners** [comment]
This is customized as part of our CHIP wheels build (see https://github.com/home-assistant-libs/chip-wheels/blob/main/0007-Use-data-as-platform-storage-location.patch). You can build the CHIP wheels from Matter SDK on your own and customize for your needs.

However, ideally this should be a runtime configuration we can control from Python side. But that would require changes to the Matter SDK C++ code, from what I can tell... But  they usually are receptive of PR :wink:

**Comment by flatsiedatsie** [comment]
@agners Ah, so that's where it is. I was searching all through the code :-)

Thanks for the clear explanation. I've created a feature request with Matter, as a PR is slightly above my skill level at the moment. For now I'll just hack around it. 

@MartinHjelmare I'm running the `example` script.

Thanks you both for your great work in making experimenting with Matter more accessible.

**Comment by Sjors** [comment]
The patch was renamed (?) from 0007 to 0002: https://github.com/home-assistant-libs/chip-wheels/blob/main/0002-Use-data-as-platform-storage-location.patch
