### ISSUE TITLE
ESP32 stamp bricked after flashing through web UI?

### ISSUE THREAD

**Issue by flatsiedatsie** [home-assistant-libs/python-matter-server#152]
I purchased an ESP32 Stamp just so I could try and create a Matter test device using the UI.

I flashed it. Then I tried to use the serial console to add the wifi settings. But that didn't work. This is what I saw in the serial output:

![matter_stamp_crash](https://user-images.githubusercontent.com/805405/209702332-069ca654-1794-40a8-a5a4-c98c50ecb90b.png)

I think there was also a brief mention about the bootloader.

I went to look for any hints online. Some while later I disconnected it. Now it no longer responds to anything. The lights don't even turn on.

Perhaps I bought a lemon, or made a user error. But I thought I'd share, just in case.

**Comment by balloob** [comment]
Note that there are 2 variants of the M5Stamp. The Pico and the C3. Our website is for the C3 variant: https://nabucasa.github.io/matter-example-apps/

You should be able to flash the All Clusters app to the M5Stamp Pico.

**Comment by balloob** [comment]
flashing a new device works

**Comment by flatsiedatsie** [comment]
Well. It's a mystery then :-)

Shall I close the issue?
