### ISSUE TITLE
Cannot comission shared device

### ISSUE THREAD

**Issue by d4g** [home-assistant-libs/python-matter-server#157]
When I try to add a matter device via apple homekit via the share option, it fails:

```
Jan 06 23:41:03 matter-server docker-matter-server-start[417288]: 2023-01-06 23:41:03 matter-server chip.TOO[1] INFO Discovered Device: fd72:2a59:1819:0:censored
Jan 06 23:41:03 matter-server docker-matter-server-start[417288]: 2023-01-06 23:41:03 matter-server matter_server.server.client_handler[1] ERROR [140301820492864] Error handling message: CommandMessage(message_id='7381a647713640ddbecb3815aa9c189c', command='commission_on_network', args={'setup_pin_code': 32809censored})
Jan 06 23:41:03 matter-server docker-matter-server-start[417288]: Traceback (most recent call last):
Jan 06 23:41:03 matter-server docker-matter-server-start[417288]:   File "/usr/local/lib/python3.9/dist-packages/matter_server/server/client_handler.py", line 185, in _run_handler
Jan 06 23:41:03 matter-server docker-matter-server-start[417288]:     result = await result
Jan 06 23:41:03 matter-server docker-matter-server-start[417288]:   File "/usr/local/lib/python3.9/dist-packages/matter_server/server/device_controller.py", line 158, in commission_on_network
Jan 06 23:41:03 matter-server docker-matter-server-start[417288]:     raise NodeCommissionFailed(
Jan 06 23:41:03 matter-server docker-matter-server-start[417288]: matter_server.common.models.error.NodeCommissionFailed: Commission on network failed for node 2
```

**Comment by marcelveldt** [comment]
Sorry but there is really no information in your report that could help solve it.

- what device did you try to commission ?
- Did you try regular commissioning too ?
- Does the device support multi fabric already ?
- Do you have any other (debug) logging from the chip SDK because above error is not verbose enough

Closing this issue now. Reopen or create a new issue if you still experience problems and please let me know more details.
If you are testing this from/with Home Assistant, please us the HA issue tracker.

Thanks!

**Comment by d4g** [comment]
@marcelveldt : Please re-open the issue yourself, as I cannot re-open an issue, that I did not close. 

- Device: Eve Energy with Matter Firmware: https://www.evehome.com/en/eve-energy via HomeKit
- No, as I do not have a thread stick. As far as I understand, the thread support for the SkyConnect stick is not yet available.
- I use the sharing feature, which is built into Home-Kit. As far as I understood, if this feature is offered by a matter server, it does not have to be implemented directly into a device?
- The above error is the error from the project. If it's not verbose enough, perhaps implement additional debug logging?

I also suggest to create a template about how and what you want an issue to report, if you close issues without further notice if it does not fit your expectation.

**Comment by marcelveldt** [comment]
This is the repo of the library we maintain for the HA support of Matter. For enduser support, best to use the HA issue tracker, that also has the templates setup you suggest.

When you put the device in commission mode from Apple HomeKit you can use that code to commission to HomeAssistant. Just use the regular commission button in the UI, that should work.

It's all pretty early stage and a lot still needs tobbe polished and/or better explained.

**Comment by zachberger** [comment]
I see the exact error when trying to commission a shared device. `commission_on_network` doesn't seem to be too reliable
