### ISSUE TITLE
Commissioned nodes are not loaded after a restart

### ISSUE THREAD

**Issue by ArturoGuerra** [home-assistant-libs/python-matter-server#159]
Commissioned nodes are never loaded after a controller restart because the storage controller is initialized before the compressed fabric id is known since the device controller hasn't been initialized

**Comment by hoppel118** [comment]
Did you ever solve this issue somehow?

I am discussing this with @Spartandrew18 on discord. We have the same issue.

**Comment by ArturoGuerra** [comment]
Should be fixed https://github.com/home-assistant-libs/python-matter-server/pull/160

**Comment by hoppel118** [comment]
Thanks! Do you know, when we see this fix in HAOS?

At the moment I am using 2023.1.6 with Matter server 2.0.0.

Sorry, I am completely new to Home Assistant. 😉

**Comment by ArturoGuerra** [comment]
No idea currently the latest beta of home assistant is still using version 1.0.8 and the persistency fix wasn't released till version 1.1.0 if you really want to run the matter server you could run the 1.1.0 release elsewhere and connect home assistant to it.

**Comment by hoppel118** [comment]
Ok, thanks. I have to think about it. 😃

Have a nice day
