### ISSUE TITLE
UniqueID should probably not be a mandatory attribute

### ISSUE THREAD

**Issue by kjagiello** [home-assistant-libs/python-matter-server#173]
Want to open with saying that I'm completely new to matter, so I might be misunderstanding the spec 😅 But hopefully I'm on the right track here!

I have encountered an issue when commissioning my ESP32 C3 running the light example from esp-matter (on recent commit, CHIP v1.0.0.2). Commissioning using the latest HASS results in the following stacktrace:
```
 (...)
  File "/usr/src/homeassistant/homeassistant/components/matter/entity.py", line 67, in __init__
    f"{node.unique_id}-"
  File "/usr/local/lib/python3.10/site-packages/matter_server/common/models/node.py", line 215, in unique_id
    self.get_attribute(
  File "/usr/local/lib/python3.10/site-packages/matter_server/common/models/node.py", line 152, in get_attribute
    return next(
StopIteration
```

It seems that others are affected by it as well:
- https://github.com/home-assistant/core/issues/85091
- https://github.com/home-assistant/core/issues/84807

While reading the spec (22-22349-001_Matter-1.0-Core-Specification.pdf, section 11.1.6.3), I have noticed that the Unique ID attribute within Basic Information is not mandatory, but optional, which does not seem to align with the getter here:
https://github.com/home-assistant-libs/python-matter-server/blob/510c2d51b317de54e7b13a0f7a080f9a2727ffeb/matter_server/common/models/node.py#L210-L218

Could it be that a misassumption has been made here about this attribute?

**Comment by agners** [comment]
Agreed, we cannot rely on this attribute to be present.

Also, even if its mandatory, it does not guarantee to remain static across factory reset, from the standard:

> It MAY be constructed using a permanent device identifier (such as device MAC address) as basis.
In order to prevent tracking,
• it SHOULD NOT be identical to (or easily derived from) such permanent device identifier
• it SHOULD be updated when the device is factory reset
...


Maybe using Node ID or something which derives from it (e.g. Operational Instance Name) as unique ID? The Operational Instance Name would be nice since this is used as DNS‐SD instance name.

**Comment by kjagiello** [comment]
Yeah, based on what I'm reading in the core spec, it looks like Node ID fits the bill. I guess Operational Instance Name would fit the bill too, since it consists of both Fabric ID and Node ID.

**Comment by marcelveldt** [comment]
Unique ID was mandatory in a pre-v1 stage but is now optional and it looks like most implementations abandoned it.
We are going to provide a small quick fix to switch from unique id to the node id. Unfortunately there is no 100% solid way (yet) to detect a device inter-fabric or between (re)commissions. I guess that is a problem for later :-)

**Comment by kjagiello** [comment]
Oh, that explains it! Thanks!

**Comment by marcelveldt** [comment]
Fix is in HA core. We'll remove the property within the lib later as we have a small refactor of the node class scheduled.

https://github.com/home-assistant/core/pull/86046
