### ISSUE TITLE
Keep Python 3.9 compatibility?

### ISSUE THREAD

**Issue by flatsiedatsie** [home-assistant-libs/python-matter-server#184]
I noticed in the roadmap for this awesome project that there is an notion to require Python 3.10.

I hope you'll consider keeping this project compatible with Python 3.9. Currently the Raspberry Pi comes with 3.9, so it has a great install base. I'm using it in my Matter project too (outside of the Home Assistant ecosystem), and I'm hesitant to upgrade Python to a version that Raspberry Pi OS doesn't come pre-loaded with.

**Comment by firstof9** [comment]
Containers don't need python support on the host OS.

**Comment by flatsiedatsie** [comment]
I'm not using a container though. Just a Raspberry Pi with Raspbian OS.

**Comment by firstof9** [comment]
You'd be better off using a container on a Pi, less to worry about.

**Comment by flatsiedatsie** [comment]
I had a look, and it seems Python3.9 was released in 2020. That really is relatively old, so I'm on board with the Python 3.10 choice :-D

For my project I can't use containers or virtual environments. I'm creating a [plugin](https://github.com/createcandle/matter-adapter) for the [Candle smart home controller](https://www.candlesmarthome.com/) (which is based on the [Webthings Gateway](https://github.com/webthingsio/gateway)), and these plugins can only install required packages in a sub directory called lib. In the future these plugins themselves may become containerized, but they are not currently.

Luckily I can get Candle to come pre-installed with a newer version of Python itself (I'm the lead developer), so I'm looking into that now.
