### ISSUE TITLE
When handling a bridge native endpoints are ignored  

### ISSUE THREAD

**Issue by ArturoGuerra** [home-assistant-libs/python-matter-server#185]
https://github.com/home-assistant-libs/python-matter-server/blob/6d38b82b6cd1103e1832808c8caf165d0ad079fe/matter_server/common/models/node.py#L123-L129

**Comment by MartinHjelmare** [comment]
Please clarify the issue title and description what the problem is, and what your expectation is. Use a shorter title and a longer description.

**Comment by ArturoGuerra** [comment]
Issue is that the `MatterNode` `__post_init__` method ignores all native endpoints if it detects the root device is a matter bridge and this behavior is incorrect as a matter bridge can be both a bridge and a matter device with its own functionality

**Comment by balloob** [comment]
Is this pure theoretical or have you encountered a device/service that exposes itself as such?

**Comment by ArturoGuerra** [comment]
This is entirely a theoretical issue for now as I don't think there are any matter bridges out there could do any of this but it's a real possibility once things like smart speakers are added to the spec
