### ISSUE TITLE
Suggestion: return command string in websocket response

### ISSUE THREAD

**Issue by flatsiedatsie** [home-assistant-libs/python-matter-server#186]
Yesterday I got a little further, and realised that when I send verious commands to the server, the response is something like this:

```
client: on_message: {
  "message_id": "1",
  "result": something,
  "_type": "matter_server.common.models.message.SuccessResultMessage"
}
```

The trouble for me is that this response doesn't clearly indicate what the original command was. For example, both "set wifi credentials" and "get_nodes" return the same `_type`, namely `"message.SuccessResultMessage"`. 

What is the intended way of knowing that the message was a response to command X or command Y? Are you supposed to create an array to keep track of message numbers and which commands they correlate with?

Perhaps it would be nice to add an attribute like:

`"response_to":"get_nodes"`

For me it would simplify routing of incoming messages if they were more distinctly labeled.

**Comment by marcelveldt** [comment]
You need to send the message_id for that. Take a look at the client for a clear example how that works.

**Comment by flatsiedatsie** [comment]
Ah, I assumed the message_id was an incrementing number. If it can be anything, that's perfect!
