### ISSUE TITLE
No commission device service in Home Assistant

### ISSUE THREAD

**Issue by flatsiedatsie** [home-assistant-libs/python-matter-server#192]
Sorry to bother you again. I've been trying to get Home Assistant (latest HAOS) to pair with the Tapo P125M Mini plug, which I imported from the US to NL.

I've taken these steps:
- Enabled advanced mode
- Installed the Matter Server addon
- Created the Matter integration. Checked the box to let Home Assistant manage it.
- Set WiFi credentials (I did not see a "settings saved succesfully" confirmation, but don't know if I should have)

When I go to Developer options -> Services I see the option to `open a commissioning window`, but I don't see the option to `commission a device` (which [this video](https://youtu.be/BTyWGsO_Nb0?t=655) implies I should have).

Do you have any suggestions on how to tackle this?

I would be happy to help write documentation.

**Comment by balloob** [comment]
That video is 7 months old. It's all in the Matter panel now, and there they will be removed unless you're running nightly builds. All commissioning for users is happening via our Android and iOS apps (also triggered via the Matter panel or as a "Share Matter device" action from other Matter apps on Android).
