### ISSUE TITLE
Add a way to send extra arguments through the send_device_command method

### ISSUE THREAD

**Issue by ArturoGuerra** [home-assistant-libs/python-matter-server#193]
Currently it's not possible to implement devices like Door Locks since they require extra arguments like `timedRequestTImeoutMs`

https://github.com/home-assistant-libs/python-matter-server/blob/6d38b82b6cd1103e1832808c8caf165d0ad079fe/matter_server/client/client.py#L168-L178

![timedRequestTimeoutMs Example](https://i.arturonet.com/cHlmbZsKLA.png)

**Comment by ArturoGuerra** [comment]
https://github.com/home-assistant-libs/python-matter-server/blob/6d38b82b6cd1103e1832808c8caf165d0ad079fe/matter_server/server/device_controller.py#L272-L279
https://github.com/project-chip/connectedhomeip/blob/4895dc6518584a9a2e1a45960eedf183ee58370b/src/controller/python/chip/ChipDeviceCtrl.py#L873-L895

**Comment by MartinHjelmare** [comment]
Do you have some doc links for how to call door locks?

**Comment by ArturoGuerra** [comment]
I wasn't able to find any docs related to this, the only way I was able to find the issue and test it was by setting up a vm running the test lock device provided by the chip controller and testing it with the python matter controller cli they provide.

It raises this error if a value for `timedRequestTImeoutMs` is not provided.
https://github.com/project-chip/connectedhomeip/blob/bbfd5d6275f508f1e7779385a2ad974930cf9cfb/src/controller/python/chip/clusters/Command.py#L160-L161
