### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by vladimir-aubrecht** [home-assistant-libs/python-matter-server#196]
Hi, could somebody please help me by pointing me to API documentation?

I can see some info when performing GET / http request, but don't know how to ask server for other actions like listing all nodes, etc.

**Comment by balloob** [comment]
There is a websocket on `/ws`. However do note that the API is not stable and we expect to make breaking changes soon. If you stick to using the client in this repo, the upgrade should be relatively easy probably.

**Comment by flatsiedatsie** [comment]
@vladimir-aubrecht There is some useful explanation on the readme file on the front page of this project?

I used that to create an implementation, have a look here:
https://github.com/createcandle/matter-adapter/blob/9ab547b230e886513eb0d32520bbcee74d868fa7/pkg/matter_adapter.py#L719

@balloob: could you share more about the upcoming changes?

**Comment by marcelveldt** [comment]
All info you need is right there in the readme. Also for a complete reference implementation in python you can see the client which is included in the same library and consumed by Home Assistant.

There is no traditional HTTP API, only a websocket one. Again, see the frontpage.
