### ISSUE TITLE
Implement device ExtendedColorLight

### ISSUE THREAD

**Issue by balloob** [home-assistant-libs/python-matter-server#20]

**Comment by ArturoGuerra** [comment]
Does this need to be implemented on the python-matter-server side or just the home assistant component?

**Comment by MartinHjelmare** [comment]
It should be enough to update the light platform in Home Assistant Core.

Here's the mapping from device type to light entity description:

https://github.com/home-assistant/core/blob/fa7ad20372c82cc288bf4d7619fa01be90567d5d/homeassistant/components/matter/light.py#L135-L173

Then we need to make sure that turn on / off works as expected for the light.

I'm not sure what's left to do for extended color light. We already have it in the map.

**Comment by ArturoGuerra** [comment]
Yeah at this time it does turn on and off and you can adjust the brightness it's just the color part that is missing, I'll get that working since I have color lights to test it with.

**Comment by ArturoGuerra** [comment]
https://github.com/ArturoGuerra/core/tree/matterlights

it currently is missing some checks to make sure the lights support whatever feature is being changed on the matter side and the colors are not correctly mapped for either hs or xy, color temp is working correctly but min and max bounds still need to be set.

This should all be simple enough as all the data is available with the ColorControl cluster, ill finish it in the morning :)

**Comment by ArturoGuerra** [comment]
should be marked as resolved

**Comment by marcelveldt** [comment]
Hi @ArturoGuerra thanks for helping out with Matter ! Are you on discord ? Can you look me up there ? My discord username is marcelveldt#0393
