### ISSUE TITLE
Rust missing from `Dockerfile.dev`

### ISSUE THREAD

**Issue by wwelles** [home-assistant-libs/python-matter-server#214]
Having problems getting things going using the docker-compose and Dockerfile.dev. Appears like rust is missing, getting this error.

```
  Preparing metadata (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]

      Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/

      Checking for Rust toolchain....
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
ERROR: Service 'matter-server' failed to build: The command '/bin/bash -o pipefail -c pip3 install -U pip &&     pip3 install --no-cache-dir .[server]' returned a non-zero code: 1
```

**Comment by frenck** [comment]
It is not Rust that is missing, Python needs to be bumped to Python 3.10.

../Frenck

**Comment by wwelles** [comment]
I see.

I tried to use the base image for Debian 12 (bookworm), which uses Python 3.10, but caused other issues.

**Comment by ADeeds** [comment]
Not sure if there's any downsides to basing off of a dedicated python image, but the dockerfile builds for me if I use python:3.11-bullseye instead (I still can't connect to the server from the HASS frontend but I think that's just a version mismatch)

**Comment by wwelles** [comment]
Thanks for the solve @frenck, I was able to get it running using that! 

Unfortunately however, when trying to add the integration, HA now tells me: "The Matter server is not the correct version".

**Comment by frenck** [comment]
The current matter server requires Home Assistant 2023.3 (currently in beta). You can join the HA beta if you'd like @wwelles 👍

**Comment by wwelles** [comment]
Ah great, that would explain it 🤣
