### ISSUE TITLE
Updating not possible

### ISSUE THREAD

**Issue by Bart-van-Gorp** [home-assistant-libs/python-matter-server#219]
Dear,

I've tried to update the matter service to the latest version, and I get an error message that our home assistant installation has the wrong version. I'm on the latest version.

![Screenshot_20230223-141835](https://user-images.githubusercontent.com/6367588/220918725-07dbfbad-5e31-4bfb-b907-4b84c1fb0c3b.png)

Thanks in advance,

Your's sincerely,

Bart

**Comment by MartinHjelmare** [comment]
Are you on core 2023.3.0b0?

**Comment by Bart-van-Gorp** [comment]
I'm on the following version and there are no updates available.

![Screenshot_20230223-145657](https://user-images.githubusercontent.com/6367588/220928528-fffd21fb-64be-490b-9124-409b261fcedf.png)
![Screenshot_20230223-145723](https://user-images.githubusercontent.com/6367588/220928554-578b1841-3e8e-4124-b0ef-3321a8dde0bd.png)

**Comment by MartinHjelmare** [comment]
You're on core 2023.2.5. If you want to try the new Matter Server you need to enter the beta channel and update to core 2023.3.0b0.
