### ISSUE TITLE
Implement device GenericSwitch

### ISSUE THREAD

**Issue by balloob** [home-assistant-libs/python-matter-server#22]

**Comment by MattWestb** [comment]
IKEA have start using Matter ZCL commands in there new switches but then Zigbee ZCL R8 is not supporting the matter cluster number they have putting it as one manufacture one but is very likely changing that then the Zigbee ZCL is being updated and stream lined with Matters ZCL so they easy can exposing it over Matter in Dirigera then its getting matter support.
https://github.com/zigpy/zha-device-handlers/issues/2223#issuecomment-1463559657
