### ISSUE TITLE
Implement device WindowCovering

### ISSUE THREAD

**Issue by balloob** [home-assistant-libs/python-matter-server#24]

**Comment by Tuckie** [comment]
Really looking forward to this for my [Smartwing Blinds](https://www.indiegogo.com/projects/smartwings-nano-best-thread-enabled-smart-blinds#/). If you need any help testing please let me know.

**Comment by MartinHjelmare** [comment]
Do you have the device commissioned in the Fabric of the Matter config entry in Home Assistant? In that case you should be able to create a diagnostics dump, when running Home Assistant core-2023.2.0b0+, of the config entry and see the device among the nodes. Getting a diagnostics dump of the node would help us implement support.

**Comment by Tuckie** [comment]
Unfortunately they haven't shipped yet, but I will definitely do this when I have them in hand. I already have the SkyConnect ready on the HA side of things.
