### ISSUE TITLE
Switchbot + matter + home assistant 

### ISSUE THREAD

**Issue by ignacio82** [home-assistant-libs/python-matter-server#257]
I have the new switchbot hub that supports matter a some switchbot curtain drivers. After the latest update of home assistant I was finally able to pair the router with home assistant. I can see the temperature and humidity sensors, but the curtains drivers are not available. Google home has no problems seeing those, so I assume this has something to do with home assistant. Here is a screenshot in case it helps:

![Screenshot_20230406-170604](https://user-images.githubusercontent.com/1833309/230514958-d8157749-7e39-4864-b9e3-da06a9f609ad.png)

I would be happy to provide more information if that helps.

**Comment by balloob** [comment]
please download diagnostics for the Matter config entry and attach it to your report.

**Comment by ignacio82** [comment]
First time trying to download logs. Hopefully, this is what you were asking for. If not, please point to directions for how to get what you need. 

` ` ` 
{
  "home_assistant": {
    "installation_type": "Home Assistant Container",
    "version": "2023.4.0",
    "dev": false,
    "hassio": false,
    "virtualenv": false,
    "python_version": "3.10.10",
    "docker": true,
    "arch": "x86_64",
    "timezone": "America/Los_Angeles",
    "os_name": "Linux",
    "os_version": "3.10.105",
    "run_as_root": true
  },
  "custom_components": {
    "redfin": {
      "version": "1.1.4",
      "requirements": [
        "redfin==0.1.1"
      ]
    },
    "ytube_music_player": {
      "version": "20220205.01",
      "requirements": [
        "ytmusicapi==0.19.5",
        "pytube==10.5.1",
        "integrationhelper==0.2.2"
      ]
    },
    "jellyfin": {
      "version": "1.1.1",
      "requirements": [
        "jellyfin-apiclient-python==1.7.2"
      ]
    },
    "fullykiosk": {
      "version": "1.1.0",
      "requirements": [
        "python-fullykiosk==0.0.11"
      ]
    },
    "resmed_myair": {
      "version": "0.1.10",
      "requirements": [
        "beautifulsoup4",
        "PyJWT"
      ]
    },
    "dyson_local": {
      "version": "0.16.4-4",
      "requirements": [
        "libdyson==0.8.11"
      ]
    },
    "dyson_cloud": {
      "version": "0.15.0",
      "requirements": [
        "libdyson==0.8.7"
      ]
    },
    "mass": {
      "version": "2023.2.1",
      "requirements": [
        "music-assistant==1.8.7.4"
      ]
    },
    "keymaster": {
      "version": "v0.0.85",
      "requirements": []
    },
    "nest_protect": {
      "version": "0.3.8",
      "requirements": []
    },
    "deebot": {
      "version": "1.5.0",
      "requirements": [
        "deebot-client==1.6.0",
        "numpy>=1.21.2"
      ]
    },
    "hacs": {
      "version": "1.31.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "flair": {
      "version": "0.1.8.2",
      "requirements": [
        "flairaio==0.1.3"
      ]
    },
    "wyzeapi": {
      "version": "0.1.19",
      "requirements": [
        "wyzeapy==0.5.19"
      ]
    },
    "tryfi": {
      "version": "0.0.19",
      "requirements": [
        "pytryfi>=0.0.17"
      ]
    },
    "presence_simulation": {
      "version": "2.4",
      "requirements": []
    },
    "webrtc": {
      "version": "v3.1.0",
      "requirements": []
    },
    "tesla_custom": {
      "version": "3.11.0",
      "requirements": [
        "teslajsonpy==3.8.0"
      ]
    },
    "dwains_dashboard": {
      "version": "3.4.3",
      "requirements": []
    },
    "govee_lan": {
      "version": "1.0.0",
      "requirements": [
        "govee-led-wez>=0.0.14"
      ]
    },
    "alarmo": {
      "version": "v1.9.8",
      "requirements": []
    },
    "adaptive_lighting": {
      "version": "1.10.1",
      "requirements": [
        "ulid-transform"
      ]
    }
  },
  "integration_manifest": {
    "domain": "matter",
    "name": "Matter (BETA)",
    "codeowners": [
      "@home-assistant/matter"
    ],
    "config_flow": true,
    "dependencies": [
      "websocket_api"
    ],
    "documentation": "https://www.home-assistant.io/integrations/matter",
    "iot_class": "local_push",
    "requirements": [
      "python-matter-server==3.2.0"
    ],
    "is_built_in": true
  },
  "data": {
    "server": {
      "info": {
        "fabric_id": 1,
        "compressed_fabric_id": 3643899854281611669,
        "schema_version": 2,
        "min_supported_schema_version": 2,
        "sdk_version": "2023.2.2",
        "wifi_credentials_set": false,
        "thread_credentials_set": false
      },
      "nodes": [
        {
          "node_id": 4,
          "date_commissioned": "2023-04-06T14:14:56.713481",
          "last_interview": "2023-04-06T14:14:56.713488",
          "interview_version": 2,
          "available": true,
          "attributes": {
            "0/29/65533": 1,
            "0/29/0": [
              {
                "type": 22,
                "revision": 1
              }
            ],
            "0/29/1": [
              29,
              31,
              40,
              48,
              49,
              51,
              60,
              62,
              63,
              64,
              65,
              54
            ],
            "0/29/2": [],
            "0/29/3": [
              1,
              2,
              3,
              6,
              7
            ],
            "0/29/65532": 0,
            "0/29/65528": [],
            "0/29/65529": [],
            "0/29/65531": [
              65528,
              65529,
              65531,
              65533,
              0,
              1,
              2,
              3,
              65532
            ],
            "0/31/65533": 1,
            "0/31/0": [
              {
                "privilege": 0,
                "authMode": 0,
                "subjects": null,
                "targets": null,
                "fabricIndex": 1
              },
              {
                "privilege": 5,
                "authMode": 2,
                "subjects": [
                  112233
                ],
                "targets": null,
                "fabricIndex": 4
              }
            ],
            "0/31/2": 4,
            "0/31/4": 3,
            "0/31/3": 3,
            "0/31/65532": 0,
            "0/31/65528": [],
            "0/31/65529": [],
            "0/31/65531": [
              65528,
              65529,
              65531,
              65533,
              0,
              2,
              4,
              3,
              65532
            ],
            "0/40/65532": 0,
            "0/40/0": 1,
            "0/40/6": "**REDACTED**",
            "0/40/1": "SwitchBot",
            "0/40/2": 5015,
            "0/40/3": "SwitchBot Hub 2",
            "0/40/4": 2023,
            "0/40/7": 0,
            "0/40/8": "v1.0",
            "0/40/9": 5,
            "0/40/10": "v0.5",
            "0/40/19": {
              "caseSessionsPerFabric": 3,
              "subscriptionsPerFabric": 3
            },
            "0/40/65533": 1,
            "0/40/5": "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000",
            "0/40/65528": [],
            "0/40/65529": [],
            "0/40/65531": [
              65528,
              65529,
              65531,
              65532,
              0,
              6,
              1,
              2,
              3,
              4,
              7,
              8,
              9,
              10,
              19,
              65533,
              5
            ],
            "0/48/65532": 0,
            "0/48/2": 0,
            "0/48/3": 0,
            "0/48/1": {
              "failSafeExpiryLengthSeconds": 60,
              "maxCumulativeFailsafeSeconds": 900
            },
            "0/48/4": true,
            "0/48/65533": 1,
            "0/48/0": 0,
            "0/48/65528": [
              1,
              3,
              5
            ],
            "0/48/65529": [
              0,
              2,
              4
            ],
            "0/48/65531": [
              65528,
              65529,
              65531,
              65532,
              2,
              3,
              1,
              4,
              65533,
              0
            ],
            "0/49/0": 1,
            "0/49/1": [
              {
                "networkID": "bWktcmVk",
                "connected": true
              }
            ],
            "0/49/2": 10,
            "0/49/3": 30,
            "0/49/4": true,
            "0/49/5": 0,
            "0/49/6": "bWktcmVk",
            "0/49/7": null,
            "0/49/65532": 1,
            "0/49/65533": 1,
            "0/49/65528": [
              1,
              5,
              7
            ],
            "0/49/65529": [
              0,
              2,
              4,
              6,
              8
            ],
            "0/49/65531": [
              0,
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              65528,
              65529,
              65531,
              65532,
              65533
            ],
            "0/51/0": [
              {
                "name": "WIFI_STA_DEF",
                "isOperational": true,
                "offPremiseServicesReachableIPv4": null,
                "offPremiseServicesReachableIPv6": null,
                "hardwareAddress": "ZOgz9rAg",
                "IPv4Addresses": [
                  "wKhWhg=="
                ],
                "IPv6Addresses": [
                  "/oAAAAAAAABm6DP//vawIA==",
                  "/SzGOwbzagpm6DP//vawIA=="
                ],
                "type": 1
              }
            ],
            "0/51/1": 100,
            "0/51/8": false,
            "0/51/65532": 0,
            "0/51/65533": 1,
            "0/51/65528": [],
            "0/51/65529": [
              0
            ],
            "0/51/65531": [
              0,
              1,
              8,
              65528,
              65529,
              65531,
              65532,
              65533
            ],
            "0/60/65532": 0,
            "0/60/0": 0,
            "0/60/1": null,
            "0/60/2": null,
            "0/60/65533": 1,
            "0/60/65528": [],
            "0/60/65529": [
              0,
              1,
              2
            ],
            "0/60/65531": [
              65528,
              65529,
              65531,
              65532,
              0,
              1,
              2,
              65533
            ],
            "0/62/65532": 0,
            "0/62/0": [
              {
                "noc": "",
                "icac": null,
                "fabricIndex": 1
              },
              {
                "noc": "FTABAQEkAgE3AyQTAhgmBIAigScmBYAlTTo3BiQVASQRBBgkBwEkCAEwCUEEEoazO4trkCUA0haOB7oH/8t3OzFaeP7hBVr/w6BwnJFsBf/kTRfljn8vDe5FQzfN2F+xruZ5AHIDoydl2LaNaTcKNQEoARgkAgE2AwQCBAEYMAQUqlHXKM42q67tdKklzOlH9ijKOIowBRSjWxCXKLELq5lbWpq1TxOfB0IuARgwC0ClTBH/jDxZ5DAvCUaZVxCc1/3n6DPqsjIMoN4VoUu1w8b01ZXcbHyzt5IUhB3dYgwqrFOPBtviLvssFvToUkuDGA==",
                "icac": "FTABAQEkAgE3AyQUARgmBIAigScmBYAlTTo3BiQTAhgkBwEkCAEwCUEE+uts9mtRBy8k8KNjGyqO0ujD1jtFyu5N45QOCOBx5CqEz8FSiJLGMNPVv8cjv120mgVqGl7jLJR/hPRPtguqBDcKNQEpARgkAmAwBBSjWxCXKLELq5lbWpq1TxOfB0IuATAFFNVe4OOZgVGJ6mXE0K0Xlcl4EI+UGDALQNIv4C2uxDZYj8hpajzmmvErpH6CZVdlSCgeGGTe/c46kkyxLa11OmI0l5sesBzG2iuLtfJhbEZ7mjCWoC+o0isY",
                "fabricIndex": 4
              }
            ],
            "0/62/2": 5,
            "0/62/3": 2,
            "0/62/1": [
              {
                "rootPublicKey": "BFs332VJwg3I1yKmuKy2YKinZM57r2xsIk9+6ENJaErX2An/ZQAz0VJ9zx+6rGqcOti0HtrJCfe1x2D9VCyJI3U=",
                "vendorId": 24582,
                "fabricId": 3577120157468044096,
                "nodeId": 2582142107,
                "label": "",
                "fabricIndex": 1
              },
              {
                "rootPublicKey": "BPe5OWhKs3Y0mC5MpIUzFjy7sC2n5hxzt+vs+iSqO9GEPfgIC6yjStiIK6F3vZVtyi9fxfXH3+XsJoIjiHlyH8w=",
                "vendorId": 65521,
                "fabricId": 1,
                "nodeId": 4,
                "label": "",
                "fabricIndex": 4
              }
            ],
            "0/62/4": [
              "FTABAQEkAgE3AyyEAlVTLAcGR29vZ2xlLAELTWF0dGVyIFJvb3QnFAEAAAD+////GCYEf9JDKSYFf5Rb5TcGLIQCVVMsBwZHb29nbGUsAQtNYXR0ZXIgUm9vdCcUAQAAAP7///8YJAcBJAgBMAlBBFs332VJwg3I1yKmuKy2YKinZM57r2xsIk9+6ENJaErX2An/ZQAz0VJ9zx+6rGqcOti0HtrJCfe1x2D9VCyJI3U3CjUBKQEkAgEYJAJgMAQUcsIB91cZE7NIygDKe0X0d0ZoyX4wBRRywgH3VxkTs0jKAMp7RfR3RmjJfhgwC0BlFksWat/xjBVhCozpG9cD6cH2d7cRzhM1BRUt8NoVERZ1rFWRzueGhRzdnv2tKWZ0vryyo6Mgm83nswnbVSxvGA==",
              "FTABAQEkAgE3AyQUARgmBIAigScmBYAlTTo3BiQUARgkBwEkCAEwCUEE97k5aEqzdjSYLkykhTMWPLuwLafmHHO36+z6JKo70YQ9+AgLrKNK2IgroXe9lW3KL1/F9cff5ewmgiOIeXIfzDcKNQEpARgkAmAwBBTVXuDjmYFRieplxNCtF5XJeBCPlDAFFNVe4OOZgVGJ6mXE0K0Xlcl4EI+UGDALQHhsUkNC1SG/fjNJWxivOo+hFKHbrODsZO64JNCbqWp4SyRCY0FRJD/dweTBpgIR01dcx00uIS7/aSffGvVEOuYY"
            ],
            "0/62/5": 4,
            "0/62/65533": 1,
            "0/62/65528": [
              1,
              3,
              5,
              8
            ],
            "0/62/65529": [
              0,
              2,
              4,
              6,
              7,
              9,
              10,
              11
            ],
            "0/62/65531": [
              65528,
              65529,
              65531,
              65532,
              0,
              2,
              3,
              1,
              4,
              5,
              65533
            ],
            "0/63/65532": 0,
            "0/63/65533": 1,
            "0/63/0": [],
            "0/63/1": [],
            "0/63/2": 3,
            "0/63/3": 3,
            "0/63/65528": [
              2,
              5
            ],
            "0/63/65529": [
              0,
              1,
              3,
              4
            ],
            "0/63/65531": [
              65528,
              65529,
              65531,
              65532,
              65533,
              0,
              1,
              2,
              3
            ],
            "0/64/65532": 0,
            "0/64/0": [],
            "0/64/65533": 1,
            "0/64/65528": [],
            "0/64/65529": [],
            "0/64/65531": [
              65528,
              65529,
              65531,
              65532,
              0,
              65533
            ],
            "0/65/65532": 0,
            "0/65/0": [],
            "0/65/65533": 1,
            "0/65/65528": [],
            "0/65/65529": [],
            "0/65/65531": [
              65528,
              65529,
              65531,
              65532,
              0,
              65533
            ],
            "0/54/65532": 0,
            "0/54/0": "BEIaNX8h",
            "0/54/1": 4,
            "0/54/2": 3,
            "0/54/3": 10,
            "0/54/4": -37,
            "0/54/65533": 1,
            "0/54/65528": [],
            "0/54/65529": [],
            "0/54/65531": [
              65528,
              65529,
              65531,
              65532,
              0,
              1,
              2,
              3,
              4,
              65533
            ],
            "1/29/65533": 1,
            "1/29/0": [
              {
                "type": 14,
                "revision": 1
              }
            ],
            "1/29/1": [
              29
            ],
            "1/29/2": [],
            "1/29/3": [
              2,
              3,
              6,
              7
            ],
            "1/29/65532": 0,
            "1/29/65528": [],
            "1/29/65529": [],
            "1/29/65531": [
              65528,
              65529,
              65531,
              65533,
              0,
              1,
              2,
              3,
              65532
            ],
            "2/29/65533": 1,
            "2/29/0": [
              {
                "type": 19,
                "revision": 1
              },
              {
                "type": 775,
                "revision": 2
              }
            ],
            "2/29/1": [
              29,
              57,
              3,
              1029
            ],
            "2/29/2": [],
            "2/29/3": [],
            "2/29/65532": 0,
            "2/29/65528": [],
            "2/29/65529": [],
            "2/29/65531": [
              65528,
              65529,
              65531,
              65533,
              0,
              1,
              2,
              3,
              65532
            ],
            "2/57/65532": 0,
            "2/57/65533": 1,
            "2/57/17": true,
            "2/57/65528": [],
            "2/57/65529": [],
            "2/57/65531": [
              65528,
              65529,
              65531,
              65532,
              65533,
              17
            ],
            "2/3/65532": 0,
            "2/3/65533": 4,
            "2/3/0": 0,
            "2/3/1": 0,
            "2/3/65528": [],
            "2/3/65529": [
              0
            ],
            "2/3/65531": [
              65528,
              65529,
              65531,
              65532,
              65533,
              0,
              1
            ],
            "2/1029/65532": 0,
            "2/1029/65533": 4,
            "2/1029/0": 4300,
            "2/1029/1": null,
            "2/1029/2": null,
            "2/1029/65528": [],
            "2/1029/65529": [],
            "2/1029/65531": [
              65528,
              65529,
              65531,
              65532,
              65533,
              0,
              1,
              2
            ],
            "3/29/65533": 1,
            "3/29/0": [
              {
                "type": 19,
                "revision": 1
              },
              {
                "type": 770,
                "revision": 2
              }
            ],
            "3/29/1": [
              29,
              57,
              3,
              1026
            ],
            "3/29/2": [],
            "3/29/3": [],
            "3/29/65532": 0,
            "3/29/65528": [],
            "3/29/65529": [],
            "3/29/65531": [
              65528,
              65529,
              65531,
              65533,
              0,
              1,
              2,
              3,
              65532
            ],
            "3/57/65532": 0,
            "3/57/65533": 1,
            "3/57/17": true,
            "3/57/65528": [],
            "3/57/65529": [],
            "3/57/65531": [
              65528,
              65529,
              65531,
              65532,
              65533,
              17
            ],
            "3/3/65532": 0,
            "3/3/65533": 4,
            "3/3/0": 0,
            "3/3/1": 0,
            "3/3/65528": [],
            "3/3/65529": [
              0
            ],
            "3/3/65531": [
              65528,
              65529,
              65531,
              65532,
              65533,
              0,
              1
            ],
            "3/1026/65532": 0,
            "3/1026/65533": 4,
            "3/1026/0": 2250,
            "3/1026/1": null,
            "3/1026/2": null,
            "3/1026/65528": [],
            "3/1026/65529": [],
            "3/1026/65531": [
              65528,
              65529,
              65531,
              65532,
              65533,
              0,
              1,
              2
            ],
            "4/29/65533": 1,
            "4/29/0": [
              {
                "type": 19,
                "revision": 1
              },
              {
                "type": 514,
                "revision": 2
              }
            ],
            "4/29/1": [
              29,
              57,
              3,
              258
            ],
            "4/29/2": [],
            "4/29/3": [],
            "4/29/65532": 0,
            "4/29/65528": [],
            "4/29/65529": [],
            "4/29/65531": [
              65528,
              65529,
              65531,
              65533,
              0,
              1,
              2,
              3,
              65532
            ],
            "4/57/65532": 0,
            "4/57/65533": 1,
            "4/57/17": true,
            "4/57/65528": [],
            "4/57/65529": [],
            "4/57/65531": [
              65528,
              65529,
              65531,
              65532,
              65533,
              17
            ],
            "4/3/65532": 0,
            "4/3/65533": 4,
            "4/3/0": 0,
            "4/3/1": 0,
            "4/3/65528": [],
            "4/3/65529": [
              0
            ],
            "4/3/65531": [
              65528,
              65529,
              65531,
              65532,
              65533,
              0,
              1
            ],
            "4/258/65532": 5,
            "4/258/65533": 5,
            "4/258/0": 4,
            "4/258/7": 9,
            "4/258/10": 0,
            "4/258/13": 14,
            "4/258/23": 0,
            "4/258/5": 0,
            "4/258/8": 100,
            "4/258/11": 10000,
            "4/258/14": 10000,
            "4/258/65528": [],
            "4/258/65529": [
              0,
              1,
              2,
              5
            ],
            "4/258/65531": [
              65528,
              65529,
              65531,
              65532,
              65533,
              0,
              7,
              10,
              13,
              23,
              5,
              8,
              11,
              14
            ],
            "5/29/65533": 1,
            "5/29/0": [
              {
                "type": 19,
                "revision": 1
              },
              {
                "type": 514,
                "revision": 2
              }
            ],
            "5/29/1": [
              29,
              57,
              3,
              258
            ],
            "5/29/2": [],
            "5/29/3": [],
            "5/29/65532": 0,
            "5/29/65528": [],
            "5/29/65529": [],
            "5/29/65531": [
              65528,
              65529,
              65531,
              65533,
              0,
              1,
              2,
              3,
              65532
            ],
            "5/57/65532": 0,
            "5/57/65533": 1,
            "5/57/17": true,
            "5/57/65528": [],
            "5/57/65529": [],
            "5/57/65531": [
              65528,
              65529,
              65531,
              65532,
              65533,
              17
            ],
            "5/3/65532": 0,
            "5/3/65533": 4,
            "5/3/0": 0,
            "5/3/1": 0,
            "5/3/65528": [],
            "5/3/65529": [
              0
            ],
            "5/3/65531": [
              65528,
              65529,
              65531,
              65532,
              65533,
              0,
              1
            ],
            "5/258/65532": 5,
            "5/258/65533": 5,
            "5/258/0": 4,
            "5/258/7": 9,
            "5/258/10": 0,
            "5/258/13": 14,
            "5/258/23": 0,
            "5/258/5": 0,
            "5/258/8": 97,
            "5/258/11": 9700,
            "5/258/14": 9700,
            "5/258/65528": [],
            "5/258/65529": [
              0,
              1,
              2,
              5
            ],
            "5/258/65531": [
              65528,
              65529,
              65531,
              65532,
              65533,
              0,
              7,
              10,
              13,
              23,
              5,
              8,
              11,
              14
            ],
            "6/258/65533": 5,
            "6/57/65531": [
              65528,
              65529,
              65531,
              65532,
              65533,
              17
            ],
            "6/3/65529": [
              0
            ],
            "6/3/0": 0,
            "6/258/5": 0,
            "6/258/11": 10000,
            "6/29/65531": [
              65528,
              65529,
              65531,
              65533,
              0,
              1,
              2,
              3,
              65532
            ],
            "6/258/7": 9,
            "6/258/65531": [
              65528,
              65529,
              65531,
              65532,
              65533,
              0,
              7,
              10,
              13,
              23,
              5,
              8,
              11,
              14
            ],
            "6/57/17": true,
            "6/258/65532": 5,
            "6/3/65533": 4,
            "6/258/13": 14,
            "6/57/65528": [],
            "6/29/65533": 1,
            "6/258/8": 100,
            "6/29/65528": [],
            "6/57/65529": [],
            "6/3/65532": 0,
            "6/57/65533": 1,
            "6/29/0": [
              {
                "type": 19,
                "revision": 1
              },
              {
                "type": 514,
                "revision": 2
              }
            ],
            "6/3/65528": [],
            "6/29/2": [],
            "6/258/10": 0,
            "6/258/14": 10000,
            "6/29/65532": 0,
            "6/29/1": [
              29,
              57,
              3,
              258
            ],
            "6/29/65529": [],
            "6/258/0": 4,
            "6/3/1": 0,
            "6/258/23": 0,
            "6/29/3": [],
            "6/258/65529": [
              0,
              1,
              2,
              5
            ],
            "6/3/65531": [
              65528,
              65529,
              65531,
              65532,
              65533,
              0,
              1
            ],
            "6/258/65528": [],
            "6/57/65532": 0,
            "7/57/65531": [
              65528,
              65529,
              65531,
              65532,
              65533,
              17
            ],
            "7/3/65532": 0,
            "7/258/14": 9700,
            "7/57/65529": [],
            "7/258/65529": [
              0,
              1,
              2,
              5
            ],
            "7/29/0": [
              {
                "type": 19,
                "revision": 1
              },
              {
                "type": 514,
                "revision": 2
              }
            ],
            "7/29/65529": [],
            "7/258/65531": [
              65528,
              65529,
              65531,
              65532,
              65533,
              0,
              7,
              10,
              13,
              23,
              5,
              8,
              11,
              14
            ],
            "7/258/65532": 5,
            "7/3/65528": [],
            "7/258/5": 0,
            "7/29/65532": 0,
            "7/258/23": 0,
            "7/3/0": 0,
            "7/258/0": 4,
            "7/29/65533": 1,
            "7/29/65528": [],
            "7/258/11": 9700,
            "7/57/65528": [],
            "7/29/2": [],
            "7/57/17": true,
            "7/29/3": [],
            "7/57/65532": 0,
            "7/57/65533": 1,
            "7/258/65533": 5,
            "7/258/13": 14,
            "7/258/10": 0,
            "7/258/8": 97,
            "7/258/7": 9,
            "7/258/65528": [],
            "7/29/1": [
              29,
              57,
              3,
              258
            ],
            "7/3/65533": 4,
            "7/3/65531": [
              65528,
              65529,
              65531,
              65532,
              65533,
              0,
              1
            ],
            "7/3/65529": [
              0
            ],
            "7/3/1": 0,
            "7/29/65531": [
              65528,
              65529,
              65531,
              65533,
              0,
              1,
              2,
              3,
              65532
            ]
          }
        }
      ],
      "events": [
        {
          "Header": {
            "EndpointId": 0,
            "ClusterId": 54,
            "EventId": 2,
            "EventNumber": 5767170,
            "Priority": 1,
            "Timestamp": 3250,
            "TimestampType": 0
          },
          "Status": 0,
          "Data": {
            "connectionStatus": 0
          }
        },
        {
          "Header": {
            "EndpointId": 0,
            "ClusterId": 40,
            "EventId": 0,
            "EventNumber": 5832704,
            "Priority": 2,
            "Timestamp": 1157,
            "TimestampType": 0
          },
          "Status": 0,
          "Data": {
            "softwareVersion": 5
          }
        },
        {
          "Header": {
            "EndpointId": 0,
            "ClusterId": 51,
            "EventId": 3,
            "EventNumber": 5832705,
            "Priority": 2,
            "Timestamp": 1158,
            "TimestampType": 0
          },
          "Status": 0,
          "Data": {
            "bootReason": 1
          }
        },
        {
          "Header": {
            "EndpointId": 0,
            "ClusterId": 54,
            "EventId": 2,
            "EventNumber": 5832706,
            "Priority": 1,
            "Timestamp": 3255,
            "TimestampType": 0
          },
          "Status": 0,
          "Data": {
            "connectionStatus": 0
          }
        },
        {
          "Header": {
            "EndpointId": 0,
            "ClusterId": 40,
            "EventId": 0,
            "EventNumber": 5898240,
            "Priority": 2,
            "Timestamp": 1157,
            "TimestampType": 0
          },
          "Status": 0,
          "Data": {
            "softwareVersion": 5
          }
        },
        {
          "Header": {
            "EndpointId": 0,
            "ClusterId": 51,
            "EventId": 3,
            "EventNumber": 5898241,
            "Priority": 2,
            "Timestamp": 1158,
            "TimestampType": 0
          },
          "Status": 0,
          "Data": {
            "bootReason": 1
          }
        },
        {
          "Header": {
            "EndpointId": 0,
            "ClusterId": 54,
            "EventId": 2,
            "EventNumber": 5898242,
            "Priority": 1,
            "Timestamp": 3213,
            "TimestampType": 0
          },
          "Status": 0,
          "Data": {
            "connectionStatus": 0
          }
        },
        {
          "Header": {
            "EndpointId": 0,
            "ClusterId": 40,
            "EventId": 0,
            "EventNumber": 5963776,
            "Priority": 2,
            "Timestamp": 1157,
            "TimestampType": 0
          },
          "Status": 0,
          "Data": {
            "softwareVersion": 5
          }
        },
        {
          "Header": {
            "EndpointId": 0,
            "ClusterId": 51,
            "EventId": 3,
            "EventNumber": 5963777,
            "Priority": 2,
            "Timestamp": 1158,
            "TimestampType": 0
          },
          "Status": 0,
          "Data": {
            "bootReason": 1
          }
        },
        {
          "Header": {
            "EndpointId": 0,
            "ClusterId": 54,
            "EventId": 2,
            "EventNumber": 5963778,
            "Priority": 1,
            "Timestamp": 2617,
            "TimestampType": 0
          },
          "Status": 0,
          "Data": {
            "connectionStatus": 0
          }
        },
        {
          "Header": {
            "EndpointId": 0,
            "ClusterId": 40,
            "EventId": 0,
            "EventNumber": 6225920,
            "Priority": 2,
            "Timestamp": 1157,
            "TimestampType": 0
          },
          "Status": 0,
          "Data": {
            "softwareVersion": 5
          }
        },
        {
          "Header": {
            "EndpointId": 0,
            "ClusterId": 51,
            "EventId": 3,
            "EventNumber": 6225921,
            "Priority": 2,
            "Timestamp": 1158,
            "TimestampType": 0
          },
          "Status": 0,
          "Data": {
            "bootReason": 1
          }
        },
        {
          "Header": {
            "EndpointId": 0,
            "ClusterId": 54,
            "EventId": 2,
            "EventNumber": 6225922,
            "Priority": 1,
            "Timestamp": 3351,
            "TimestampType": 0
          },
          "Status": 0,
          "Data": {
            "connectionStatus": 0
          }
        },
        {
          "Header": {
            "EndpointId": 0,
            "ClusterId": 40,
            "EventId": 0,
            "EventNumber": 6291456,
            "Priority": 2,
            "Timestamp": 1215,
            "TimestampType": 0
          },
          "Status": 0,
          "Data": {
            "softwareVersion": 5
          }
        },
        {
          "Header": {
            "EndpointId": 0,
            "ClusterId": 51,
            "EventId": 3,
            "EventNumber": 6291457,
            "Priority": 2,
            "Timestamp": 1217,
            "TimestampType": 0
          },
          "Status": 0,
          "Data": {
            "bootReason": 1
          }
        },
        {
          "Header": {
            "EndpointId": 0,
            "ClusterId": 54,
            "EventId": 2,
            "EventNumber": 6291458,
            "Priority": 1,
            "Timestamp": 3434,
            "TimestampType": 0
          },
          "Status": 0,
          "Data": {
            "connectionStatus": 0
          }
        },
        {
          "Header": {
            "EndpointId": 0,
            "ClusterId": 40,
            "EventId": 0,
            "EventNumber": 6356992,
            "Priority": 2,
            "Timestamp": 1157,
            "TimestampType": 0
          },
          "Status": 0,
          "Data": {
            "softwareVersion": 5
          }
        },
        {
          "Header": {
            "EndpointId": 0,
            "ClusterId": 51,
            "EventId": 3,
            "EventNumber": 6356993,
            "Priority": 2,
            "Timestamp": 1158,
            "TimestampType": 0
          },
          "Status": 0,
          "Data": {
            "bootReason": 1
          }
        },
        {
          "Header": {
            "EndpointId": 0,
            "ClusterId": 54,
            "EventId": 2,
            "EventNumber": 6356994,
            "Priority": 1,
            "Timestamp": 3385,
            "TimestampType": 0
          },
          "Status": 0,
          "Data": {
            "connectionStatus": 0
          }
        },
        {
          "Header": {
            "EndpointId": 0,
            "ClusterId": 40,
            "EventId": 0,
            "EventNumber": 6422528,
            "Priority": 2,
            "Timestamp": 1167,
            "TimestampType": 0
          },
          "Status": 0,
          "Data": {
            "softwareVersion": 5
          }
        },
        {
          "Header": {
            "EndpointId": 0,
            "ClusterId": 51,
            "EventId": 3,
            "EventNumber": 6422529,
            "Priority": 2,
            "Timestamp": 1168,
            "TimestampType": 0
          },
          "Status": 0,
          "Data": {
            "bootReason": 1
          }
        },
        {
          "Header": {
            "EndpointId": 0,
            "ClusterId": 54,
            "EventId": 2,
            "EventNumber": 6422530,
            "Priority": 1,
            "Timestamp": 3392,
            "TimestampType": 0
          },
          "Status": 0,
          "Data": {
            "connectionStatus": 0
          }
        },
        {
          "Header": {
            "EndpointId": 0,
            "ClusterId": 40,
            "EventId": 0,
            "EventNumber": 6488064,
            "Priority": 2,
            "Timestamp": 1156,
            "TimestampType": 0
          },
          "Status": 0,
          "Data": {
            "softwareVersion": 5
          }
        },
        {
          "Header": {
            "EndpointId": 0,
            "ClusterId": 51,
            "EventId": 3,
            "EventNumber": 6488065,
            "Priority": 2,
            "Timestamp": 1158,
            "TimestampType": 0
          },
          "Status": 0,
          "Data": {
            "bootReason": 1
          }
        },
        {
          "Header": {
            "EndpointId": 0,
            "ClusterId": 54,
            "EventId": 2,
            "EventNumber": 6488066,
            "Priority": 1,
            "Timestamp": 3381,
            "TimestampType": 0
          },
          "Status": 0,
          "Data": {
            "connectionStatus": 0
          }
        }
      ]
    }
  }
}
` ` `

**Comment by marcelveldt** [comment]
As you can see in the [documentation](https://www.home-assistant.io/integrations/matter/) for the Matter integration it not yet has support for the cover platform so it is correct that your device will not show up.

Good news however is that we're actively working on exactly this platform so it will be available in the next Home Assistant release. I will use your diagnostics dump (thanks for that) to validate our implementation against real device data.

**Comment by ignacio82** [comment]
Thanks, looking forward to next release.

**Comment by marcelveldt** [comment]
Today I spent some time testing with the Switchbot Hub 2 including Curtain drivers, paired to Matter.
I fixed a small bug in our implementation, just in time for the HA 2023.5 release, which beta starts today.

More interesting though I did discover a bug in the Switchbot implementation itself and the way it has implemented the bridge support, the device information is missing for bridged devices. It's not a big deal as functionality wise everything works but it looks a bit unpolished compared to other bridges I've tested,

**Comment by ignacio82** [comment]
@marcelveldt Thanks, looking forward to testing it. Are you planning on filling a bug report with Switchbot?

**Comment by marcelveldt** [comment]
Yeah, I've received an emailaddress where I'll send my findings. Its nothing that fancy but the naming is off, hence you get some empty/meaningless names in HA for the SwitchBot devices.

**Comment by marcelveldt** [comment]
Closing this issue reports. The SwitchBot HUB works fine with HA, although they have bugs in their implementation where composed devices show up as different endpoints and no device names. We've emailed them but no response.

So maybe hopefully one day the naming and representation gets fixed but technically it works

**Comment by asjmcguire** [comment]
Since this is about Switchbot matter support in Home Assistant and specifically about window coverings - I would like to make a point here:

The Switchbot Blind Tilt detected by Bluetooth has supported features: 240, and indeed it supports the service call of ```cover.set_tilt_position``` and has an attribute of ```current_tilt_position``` however the Blind Tilt as detected over matter, has supported features: 15, and does NOT support the ```cover.set_tilt_position``` service, and it has the attribute of ```current_position``` instead.

Is this a Home Assistant issue, or a Switchbot issue? Essentially from what I can tell Home Assistant is treating the Blind Tilt as if it was a curtain rather than blinds (and changing the display as entry doesn't make any different in Home Assistant)

**Comment by marcelveldt** [comment]
@asjmcguire please create a NEW issue on the Home Assistant issue tracker, do not hijack a random existing one. Thanks!
