### ISSUE TITLE
Question: Supported server interactions

### ISSUE THREAD

**Issue by nevi-me** [home-assistant-libs/python-matter-server#259]
Hi,

I'm building an implementation of the python-matter-server that uses a Matter implementation that's independent from the CHIP megarepo. My goal is to support installing the server on a Raspberry Pi 3B (32-bit).

Firstly, would this be an appropriate place to ask some implementation questions?

My current status is that I've got the barebone websocket server working, and HomeAssistant is connected to it.
I'm currently working on DNS-SD discovery, but noticed that there's no option in HomeAssistant to discover devices.

Is this currently implemented, or can I safely skip this for now?

BTW, are there other known implementations of the server that I can also use?

**Comment by balloob** [comment]
32-bit is not supported by the Matter SDK, which means it's also not supported by the Python Matter Server.
