### ISSUE TITLE
Implement device Thermostat

### ISSUE THREAD

**Issue by balloob** [home-assistant-libs/python-matter-server#26]

**Comment by zachberger** [comment]
I'm wondering the status of this. The blog post yesterday mentioned "Today Home Assistant can control the basic operation of most Matter devices." does that include basic control of Thermostat?

**Comment by MartinHjelmare** [comment]
No. Are there any Matter Thermostat devices available?

**Comment by patrikulus** [comment]
Since now we have bridge support, there is Aqara Radiator Thermostat E1. For now it only show battery state in HA.

**Comment by balloob** [comment]
@patrikulus would you be able to share a diagnostics dump with us? It will help with implementation.

**Comment by patrikulus** [comment]
[matter-2bd17babfe20dce8992b436a555abc6b-Aqara Smart Radiator Thermostat E1-6e1532447c5d9995a6c15630881a7a58.json.txt](https://github.com/home-assistant-libs/python-matter-server/files/10875922/matter-2bd17babfe20dce8992b436a555abc6b-Aqara.Smart.Radiator.Thermostat.E1-6e1532447c5d9995a6c15630881a7a58.json.txt)
I've removed the custom extensions content and redacted the long base64(?) strings, I hope it's safe to share all the other info :)

**Comment by lboue** [comment]
There is a Linux thermostat example in [connectedhomeip repo](https://github.com/project-chip/connectedhomeip/blob/master/examples/thermostat/linux/main.cpp)

**Comment by marcelveldt** [comment]
Yes we know. Support for thermostat devices will be added in the core integration.
