### ISSUE TITLE
Window Covering commissioning breaks the server

### ISSUE THREAD

**Issue by Diegorro98** [home-assistant-libs/python-matter-server#277]
I've seen that Window Covering has been added recently (https://github.com/home-assistant-libs/python-matter-server/issues/24 was moved from **in progress** to **Done** in https://github.com/orgs/home-assistant-libs/projects/1 and also was closed).

I'm developing a device which has multiple endpoints, and one of them is a Window Covering endpoint, so to test window covering I modified esp-matter example with this [patch](https://github.com/home-assistant-libs/python-matter-server/files/11277703/wc_example.patch).
I tried to commissioning the esp32 flashed with this firmware, but suddenly the process stops ("no more logs in esp32 console, neither in Matter Server logs), an my android phone the Google service for commisioning a matter device only says "A error occurred" and lastly, at the integrations page, the Matter integration says "Retrying configuration: Matter client not ready".

Here there are the logs from the matter server: [core_matter_server.log](https://github.com/home-assistant-libs/python-matter-server/files/11277641/core_matter_server_2023-04-19T21-14-17.606Z.log)
And here is the error log shown in Home Assistant Core which I think that is the reason why the Matter server is restarting constantly.
<details>
<summary>Home Assistant Core Error log</summary>

```
Logger: homeassistant.components.matter
Source: components/matter/__init__.py:127
Integration: Matter (BETA) (documentation, issues)
First occurred: 23:05:42 (9 occurrences)
Last logged: 23:14:30

Unexpected exception: Value {'TLVValue': 31, 'Reason': None} of type <class 'dict'> is invalid for type, expected value of type <enum 'Type'>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/matter/__init__.py", line 127, in _client_listen
    await matter_client.start_listening(init_ready)
  File "/usr/local/lib/python3.10/site-packages/matter_server/client/client.py", line 289, in start_listening
    self._handle_incoming_message(msg)
  File "/usr/local/lib/python3.10/site-packages/matter_server/client/client.py", line 328, in _handle_incoming_message
    self._handle_event_message(msg)
  File "/usr/local/lib/python3.10/site-packages/matter_server/client/client.py", line 346, in _handle_event_message
    node = MatterNode(node_data)
  File "/usr/local/lib/python3.10/site-packages/matter_server/client/models/node.py", line 212, in __init__
    self.update(node_data)
  File "/usr/local/lib/python3.10/site-packages/matter_server/client/models/node.py", line 299, in update
    self.endpoints[endpoint_id] = MatterEndpoint(
  File "/usr/local/lib/python3.10/site-packages/matter_server/client/models/node.py", line 57, in __init__
    self.update(attributes_data)
  File "/usr/local/lib/python3.10/site-packages/matter_server/client/models/node.py", line 186, in update
    self.set_attribute_value(attribute_path, attribute_value)
  File "/usr/local/lib/python3.10/site-packages/matter_server/client/models/node.py", line 177, in set_attribute_value
    attribute_value = parse_value(
  File "/usr/local/lib/python3.10/site-packages/matter_server/common/helpers/util.py", line 223, in parse_value
    raise TypeError(
TypeError: Value {'TLVValue': 31, 'Reason': None} of type <class 'dict'> is invalid for type, expected value of type <enum 'Type'>
```

</details>

I even tried to commissioning the device first to Google Home and later share the device from the app to Home Assistant, but same problem happens.

Although that error, later after reinstalling home assistant to ensure is a clean install, I was able to commissioning the light example without any problem.

**Comment by ArturoGuerra** [comment]
Does it commission correctly with google home?

**Comment by Diegorro98** [comment]
Ops, maybe I explained the Google Home part wrong so it can be misunderstood 😅

I wanted to say that I was able to commission correctly to Google Home without any problem, but then when I wanted to share the device with home assistant, the same problem happened in Home Assistant.

Sorry for the misunderstanding!

**Comment by Diegorro98** [comment]
Update: I was trying again, and I discovered that maybe there were some wrong values on the firmware .
This is the patch that I used now: [new.patch](https://github.com/home-assistant-libs/python-matter-server/files/11289874/new.patch)
Although this fixes, I can't commission it yet to Home Assistant, although I'm able to commission to Google Home. I even tried to share from Google Home to Home Assistant, but didn't work neither:
[new.log](https://github.com/home-assistant-libs/python-matter-server/files/11289895/new.log)

Later I used this [patch](https://github.com/home-assistant-libs/python-matter-server/files/11289946/tilt_only.patch) and although I couldn't commission it to Home Assistant directly ([log](https://github.com/home-assistant-libs/python-matter-server/files/11289961/tilt_only_direct_commissioning.log)), I was able to commission to Google Home and surprisingly I shared successfully the device with Home Assistant. But then no entities were on the device and I couldn't control anything...

**Comment by ArturoGuerra** [comment]
are you running the latest version of HA cuz window covering support was just added for matter?

**Comment by Diegorro98** [comment]
Yep, all is up to date, even the Matter Addon (v4.3.1)

**Comment by ArturoGuerra** [comment]
could you send the diagnostics dump for the device that was created

**Comment by Diegorro98** [comment]
Sure! Here it is: [console.log](https://github.com/home-assistant-libs/python-matter-server/files/11292759/console.log)

**Comment by ArturoGuerra** [comment]
oh not from the device itself, the one HA has on the created device with no entities

**Comment by Diegorro98** [comment]
Oh sorry 😂😂 I read it too early in the morning!
Although yesterday I wasn't able to get it in Home Assistant, today I was able to replicate it. Unfortunately when I click on "Download diagnostics" there are problems on the download and it tries to download a file but it says network error, then if I tri to right click and open in a new window it shows `401: Unauthorized`. And lastly, If I try to right click and "Save as...", when it tries to dowload thenm it says "Problem downloading, authorization required".

**Comment by Diegorro98** [comment]
I just tried to get diagnostics dump using postman, first I tried to download other device diagnosis to check that bearer token and other parameters of the request were working, then after successfully getting other device diagnostics, I tried to get the Matter tilt only window covering device diagnostics dump, but it says the it returns `404: Not found`. As the url was had this format `api/diagnostics/config_entry/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/device/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx` and the other diagnostics dump I downloaded first had this format `api/diagnostics/config_entry/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx` I tried this format with the matter device, first using the second id that it is after device in url, and as I got the same fail response, I tried with the id that is before device in the url, but I also got the same fail response...

**Comment by balloob** [comment]
The one for the config entry includes all devices and will be ok to share.

**Comment by Diegorro98** [comment]
@balloob The problem is that it doesn't work (it returns a 404 error) with matter devices (or at least this matter device)

**Comment by marcelveldt** [comment]
What version of HA are you running ? Because in your first log I notice an error we fixed a while ago (but now I'm in doubt in which version of HA the patch is available).

**Comment by Diegorro98** [comment]
Home Assistant 2023.4.6
Supervisor 2023.04.0
OS 10.0
Frontend 20230411.1 - latest

And there aren't available updates

**Comment by Diegorro98** [comment]
> You can just get the diagnostics dump from the config screen (and not from the device level).

![image](https://user-images.githubusercontent.com/22046575/233933931-c77a0750-a288-4527-914b-fc8689972b98.png)
You mean here? Because I don't know any other place to download diagnostics dump.

**Comment by Diegorro98** [comment]
WHOAH, I found another place to download something, at integrations and at 3 dots on Matter integration. I think that it might be useful, so here it is:
[config_entry-matter-0d9f30a35831785f4cf4579d79aabd3e.json.txt](https://github.com/home-assistant-libs/python-matter-server/files/11308042/config_entry-matter-0d9f30a35831785f4cf4579d79aabd3e.json.txt)

**Comment by ArturoGuerra** [comment]
Okay so looking at the dump it looks like your device doesn't implement the CurrentPositionLiftPercentage attribute which is currently required for our implementation of window coverings 
https://github.com/home-assistant/core/blob/739963b5ee1a49039eb19a1831bb569dab255fcc/homeassistant/components/matter/cover.py#L149

**Comment by Diegorro98** [comment]
Oh, okey
So, as far as I know by observing the python script, there is no support for tilting covers, right?

**Comment by marcelveldt** [comment]
> Oh, okey So, as far as I know by observing the python script, there is no support for tilting covers, right?

At this point there's a very basic first implementation of cover support in the HA integration which extend as new devices become available. We could try to add the support based on your dump but testing it is very tricky because we don't exactly know how the device behaves when sending commands.

**Comment by Diegorro98** [comment]
I can help with that if you need it!

**Comment by hidaris** [comment]
> Oh, okey So, as far as I know by observing the python script, there is no support for tilting covers, right?

Yes, at present I do not have the tilt support device, if there is a later I will consider sending a pr

**Comment by Diegorro98** [comment]
If it's okey for you, I'm going to close this issue. If you want to reach me for testing, I'm in Home Assistant discord server and this is my user name: [Diegorro#8455](http://discord.com/users/168459153856004097)
