### ISSUE TITLE
Issue with CHIP Thermostat Application demo for Linux

### ISSUE THREAD

**Issue by lboue** [home-assistant-libs/python-matter-server#283]
# Issue with CHIP Thermostat Application demo for Linux in HA
The demo Matter thermostat is not usable. It is not correctly recognized by Home Assistant.
## Reproduce steps

Build [thermostat Application demo for Linux](https://github.com/project-chip/connectedhomeip/tree/master/examples/thermostat/linux) from CHIP repo.

### Env

* installation_type: Home Assistant OS
* version: 2023.5.0b2
* python_version: 3.10.11
* docker": true
* arch: aarch64
* os_version: 6.1.25
* supervisor: 2023.04.1
* host_os: Home Assistant OS 10.1

### Build
```
cd ~/connectedhomeip/examples/thermostat/linux
gn gen out/debug
ninja -C out/debug
```

### Run
```
out/thermostat/thermostat-app
```

### Pairing

[QRcode](https://project-chip.github.io/connectedhomeip/qrcode.html?data=MT%3A-24J042C00KA0648G00)

### Result
![image](https://user-images.githubusercontent.com/938089/235302121-138a2a56-1880-45cd-af71-b4841fb55736.png)

### Diag files
[matter-e87f29d9b987f939a7c2ff854db369c3-TEST_PRODUCT-4d8ca284906c1dd9b4d9f04c95f5cd27.json.txt](https://github.com/home-assistant-libs/python-matter-server/files/11359164/matter-e87f29d9b987f939a7c2ff854db369c3-TEST_PRODUCT-4d8ca284906c1dd9b4d9f04c95f5cd27.json.txt)
[matter-e87f29d9b987f939a7c2ff854db369c3-TEST_PRODUCT-2f44350fdde3804ae0bda2e8c73a231d.json.txt](https://github.com/home-assistant-libs/python-matter-server/files/11359165/matter-e87f29d9b987f939a7c2ff854db369c3-TEST_PRODUCT-2f44350fdde3804ae0bda2e8c73a231d.json.txt)

## Compare

The same demo application is recognized correctly by iOS 16.5 beta

**Comment by hidaris** [comment]
Currently ha is not adapted to MATTER thermostats

**Comment by lboue** [comment]
Thank you for this explanation.

**Comment by marcelveldt** [comment]
You could have seen this in the documentation: https://www.home-assistant.io/integrations/matter/#current-state-of-the-integration
