### ISSUE TITLE
How to write attributes from clients

### ISSUE THREAD

**Issue by vinhpn96** [home-assistant-libs/python-matter-server#285]
Hi
I'm developing fan control integration, but this cluster don't have any commands to set speed. I would like to set speed attribute but python-matter-server don't support any API to do it.
Similarly, I think we should have `APICommand.WRITE_ATTRIBUTE`
```
@api_command(APICommand.WRITE_ATTRIBUTE)
    async def write_attribute(self, node_id: int, endpoint: int, attribute: ClusterAttributeDescriptor, timedRequestTimeoutMs: int = None, interactionTimeoutMs: int = None):
        """Write a attribute on a target node."""
        LOGGER.info("Write Attributes node_id: %s", node_id)
        attributes = [(endpoint, attribute)]
        return await self.chip_controller.WriteAttribute(
            nodeid=node_id,
            attributes=attributes,
            timedRequestTimeoutMs=timedRequestTimeoutMs,
            interactionTimeoutMs=interactionTimeoutMs,
        )
```

**Comment by marcelveldt** [comment]
We are currently working on some other aspects but we can add the write attributes feature after that. If you are in a rush, feel free to PR the addition.

**Comment by hidaris** [comment]
> We are currently working on some other aspects but we can add the write attributes feature after that. If you are in a rush, feel free to PR the addition.

I can send a PR to add it recently.

**Comment by vinhpn96** [comment]
@marcelveldt how can I become a contributor? how can I create PR?
@hidaris please send your PR to implement this feature. Thanks

**Comment by hidaris** [comment]
> @marcelveldt how can I become a contributor? how can I create PR? @hidaris please send your PR to implement this feature. Thanks

Hi, I implemented this part locally, but I'm debugging the Thermostat integration these two days, so I don't have time to submit for now, if you're in a hurry, I'll see about sending a PR this weekend

**Comment by vinhpn96** [comment]
> > @marcelveldt how can I become a contributor? how can I create PR? @hidaris please send your PR to implement this feature. Thanks
> 
> Hi, I implemented this part locally, but I'm debugging the Thermostat integration these two days, so I don't have time to submit for now, if you're in a hurry, I'll see about sending a PR this weekend

Thanks a lot.
in fact, I implemented both `write_attribute` and `Thermostat`, `FanControl` integration locally, but I don't know how I can create PR and become a contributor :(((

**Comment by marcelveldt** [comment]
@vinhpn96 You can just open a PR here if its server related. If you want to contribute to the Home Assistant project (for he integration part), simply open a PR on the core project here: https://github.com/home-assistant/core/pulls

**Comment by marcelveldt** [comment]
@hidaris are you on discord ?

**Comment by hidaris** [comment]
> @hidaris are you on discord ?

I’m on Discord, but not in the ha server. Can you add me? My username is hidaris#7947
