### ISSUE TITLE
Is it possible to commission the controller?

### ISSUE THREAD

**Issue by skison** [home-assistant-libs/python-matter-server#290]
I'm using this server implementation on my Ubuntu machine to control some real Matter devices on my local network, and it's working great! However, I'm trying to see if there is a way to commission the controller device itself, but I don't see any instructions here on how to do that, if it's even possible.

Is it possible to commission the controller in its current state, and if so, how? If not, how would one go about implementing that feature? My understanding is that a matter controller device needs to exist as a node on the fabric with admin privileges, so I assume that is how it is structured currently, but please let me know if I'm mistaken.

**Comment by hidaris** [comment]
Based on my understanding of the spec, you cannot use controller commission to commission another controller.

**Comment by marcelveldt** [comment]
You can not commission a controller itself, only Matter devices.
