### ISSUE TITLE
Error when trying to install in HA

### ISSUE THREAD

**Issue by PvdGulik** [home-assistant-libs/python-matter-server#310]
Goodmorning,

When I try to install Python-matter-server in HA, I get this error.

<Integration home-assistant-libs/python-matter-server> Repository structure for 3.4.2 is not compliant

What to do?

Thanks!

Home Assistant 2023.5.4
Supervisor 2023.04.1
Operating System 10.2
Frontend-versie: 20230503.3 - latest
Matter Server, Current version: 4.5.1

**Comment by marcelveldt** [comment]
Did you follow the installation instructions from the documentation ?
https://www.home-assistant.io/integrations/matter/

**Comment by PvdGulik** [comment]
I followed this one:
https://docs.google.com/document/d/1MldgA337wHTEx-vPkoxlCqKHrhVm5QIcHV32iLsv_2k/edit

I'll try yours ;-)

**Comment by marcelveldt** [comment]
So those big fat letters at the top "OUTDATED" were too small ;-)
