### ISSUE TITLE
No-issue: collaboration invite

### ISSUE THREAD

**Issue by Apollon77** [home-assistant-libs/python-matter-server#314]
Hello,

sorry for creating a non-issue. Please simply close it if that is not interesting for you.

I‘m one of the maintainers of matter.js and we implement matter protocol in JavaScript/typescript.

To support the open source community in developing with and for matter I also created a discord called „matter-integrators“ where I would like to invite you. There are already other open source projects like the tasmota matter implementations, matter-es in and beside building a developer community it also started to be a good place to exchange opinions on matter specs and how to read/interpret it ;-).

I could think that also having your folks in there could improve the collaboration. 

Thank you and maybe see you there ;-)

Ingo

**Comment by Apollon77** [comment]
Discord link: https://discord.gg/fSHFGnNUMw

**Comment by marcelveldt** [comment]
Thanks for the invite! A couple of us joined the server
