### ISSUE TITLE
HA | Aqara M2 | Sensor Names

### ISSUE THREAD

**Issue by rerpires** [home-assistant-libs/python-matter-server#348]
Hi, 

It was pretty simple to install docker and integrate into HA. Using HA in Docker also. 

Hi have several diferent sensors in my AQARA M2 HUB. They are all correctly named in the AQARA app. Although when they appear in HA they are all with the same name. I could rename them manualy, but I can't find in HA any device ID or something specific to match with the device ID in the app. 

Is there a way to find that information inside HA ? 

thanks 

Rui

**Comment by lboue** [comment]
@rerpires 
You should check the JSON Matter diagnostic file. Aqara doesn't exports devices name to Matter fabric.

**Comment by marcelveldt** [comment]
lboue is correct, The Aqara hub doesnt expose this info to Matter so this is out of our control.
