### ISSUE TITLE
Unable to subscribe to EventType.NODE_EVENT on client

### ISSUE THREAD

**Issue by evanjarrett** [home-assistant-libs/python-matter-server#349]
I was debugging door jammed events in hass-core for my yale lock, but I think the issue is in this repo.

I'm trying to subscribe to events like so in MatterEntity, but nothing seems to trigger it.
```
        self._unsubscribes.append(
            self.matter_client.subscribe_events(
                callback=self._on_lock_event,
                event_filter=EventType.NODE_EVENT,
                node_filter=self._endpoint.node.node_id,
            )
        )
```

These are the debug logs from matter server addon

> 2023-07-06 20:30:10 core-matter-server matter_server.server.device_controller.[node 10][126] DEBUG Received node event: EventReadResult(Header=EventHeader(EndpointId=1, ClusterId=257, EventId=0, EventNumber=65642, Priority=<EventPriority.INFO: 2>, Timestamp=1565269046, TimestampType=<EventTimestampType.SYSTEM: 0>), Status=<Status.Success: 0>, Data=DoorLock.Events.DoorLockAlarm(alarmCode=<AlarmCodeEnum.kLockJammed: 0>)) - transaction: <Subscription (Id=1046584230)>
> 2023-07-06 20:30:10 core-matter-server matter_server.server.device_controller.[node 10][126] DEBUG Attribute updated: TypedAttributePath(ClusterType=<class 'chip.clusters.Objects.DoorLock'>, AttributeType=<class 'chip.clusters.Objects.DoorLock.Attributes.LockState'>, AttributeName='lockState', Path=AttributePath(EndpointId=1, ClusterId=257, AttributeId=0)) - old value: 2 - new value: 0
> 

You can see it is hitting the debug line here https://github.com/home-assistant-libs/python-matter-server/blob/main/matter_server/server/device_controller.py#L671

But the only event the client side receives is the ATTRIBUTE_UPDATED that follows it. This was after removing the event_filter so that all events are sent to my `_on_lock_event` function.

> 2023-07-06 21:30:06.918 DEBUG (MainThread) [custom_components.matter] Lock state: 0 for lock.yale_matter_smart_module
> 2023-07-06 21:30:06.926 DEBUG (MainThread) [custom_components.matter] on lock event: EventType.ATTRIBUTE_UPDATED for 0

**Comment by marcelveldt** [comment]
You need to subscribe to it by adding the attributes in the discovery schema

**Comment by marcelveldt** [comment]
https://github.com/home-assistant/core/blob/dev/homeassistant/components/matter/lock.py#L173

Make sure that all required attributes that need to be watched are either in the required_attributes or optional_attributes and the event subscription will be automatically handled,

**Comment by marcelveldt** [comment]
Ah you want to watch a nod event and not attribute change, that is something new. Can you enlighten me why and how ?

**Comment by marcelveldt** [comment]
There is an ongoing discussion about forwarding device events to HA. Currently that is NOT implemented. The idea is that that will be a new entity type for events as a global new HA feature. Not only interesting for Matter but for a lot more integrations. So this is not a bug but more like a feature request. Let's wait until the HA feature is implemented and then we will implement this in the Matter integration as well.

**Comment by evanjarrett** [comment]
I would like to know if the deadbolt/lock was able to close all the way. If I prevent it from latching, the keypad flashes, and beeps a few times trying to close the lock, but eventually gives up and fires off a doorlockalarm.
As far as I can tell the only way to know that is if the `DoorLock.Events.DoorLockAlarm` event was triggered since there is no LockState value for it:
```
class DlLockState(MatterIntEnum):
            kNotFullyLocked = 0x00
            kLocked = 0x01
            kUnlocked = 0x02
            kUnlatched = 0x03
            # All received enum values that are not listed above will be mapped
            # to kUnknownEnumValue. This is a helper enum value that should only
            # be used by code to process how it handles receiving and unknown
            # enum value. This specific should never be transmitted.
            kUnknownEnumValue = 4,
```
The attribute is set to 0 (kNotFullyLocked) which in home assistant is labeled as "Locking". But the lock is no longer in the process of locking.

**Comment by marcelveldt** [comment]
Yeah, I think you have a very valid usecase. Let's wait for the discussion about events in HA so we know where to land events the right way. Previously HA integrations would just have forwarded events to the HA eventbus (just like we do with e.g. Hue, Z-Wave etc.) but that is very user unfriendly so we want to do this with a special entity which is visualized and also allows to show the history of events. 

Because this change is so close of being implemented, we decided to hold off implementing "the old" way of doing it for Matter. So for now all I ask is a little bit of patience as this is being sorted out.
