### ISSUE TITLE
Some bridged multi-sensor devices reports inconsistent product names

### ISSUE THREAD

**Issue by lboue** [home-assistant-libs/python-matter-server#352]
# Summary

Some multi-sensor devices reports inconsistent product names. In my case it came from an Aqara Hub E1 Matter bridge.
I should have a product name equal to 'Aqara Temperature and Humidity' from the diagnostic file.
Instead on multiple devices of the same type I get different values:

- HumiditySensor
- PowerSource
- TemperatureSensor

![image](https://github.com/home-assistant-libs/python-matter-server/assets/938089/3174f3cd-bf48-4f4b-8f5d-500621b762a6)![image](https://github.com/home-assistant-libs/python-matter-server/assets/938089/17171c51-86ec-4aeb-8017-960c736fc196)
![image](https://github.com/home-assistant-libs/python-matter-server/assets/938089/567018f8-f99f-4cb9-9b7c-d3d80812b00d)

## Env

- Home Assistant 2023.7.1
- Supervisor 2023.07.1
- Operating System 10.2
- Frontend 20230705.1
- Matter Server 4.8.2
- Aqara Hub E1 4.0.2

## Steps to reproduce

1. Enable Matter support for [Aqara Hub E1](https://www.aqara.com/en/product/hub-e1) in Aqara Home app
2. Pair Aqara Hub E1 with Apple Home ecosystem
3. Turn On pairing mode in Apple Home app to get a pairing code
4. Start pairing  Aqara Hub E1 with Home Assitant iOS app with the pairing code

## Matter diagnostic file
[matter-e87f29d9b987f939a7c2ff854db369c3-Aqara Smart Radiator Thermostat-61f40eedaa122758a3719b9c7916dd6f.json (2).txt](https://github.com/home-assistant-libs/python-matter-server/files/11985403/matter-e87f29d9b987f939a7c2ff854db369c3-Aqara.Smart.Radiator.Thermostat-61f40eedaa122758a3719b9c7916dd6f.json.2.txt)

**AS008 Aqara sensor temperature**

```
        "4/47/65529": [],
        "4/47/15": false,
        "4/47/19": "CR2032",
        "4/47/14": 0,
        "4/47/65528": [],
        "4/47/12": 200,
        "4/47/65531": [
          0,
          1,
          2,
          11,
          12,
          14,
          15,
          16,
          19,
          25,
          65528,
          65529,
          65531,
          65532,
          65533
        ],
        "4/47/65532": 10,
        "4/47/1": 0,
        "4/47/0": 1,
        "4/47/65533": 1,
        "4/47/16": 2,
        "4/47/2": "Battery",
        "4/47/25": 1,
        "4/47/11": 3000,
        "4/57/2": 4447,
        "4/57/65528": [],
        "4/57/12": "AS008",
        "4/57/15": "158d0001a4a561",
        "4/57/65529": [],
        "4/57/17": true,
        "4/57/18": "lumi.158d0001a4a561",
        "4/57/65532": 0,
        "4/57/5": "Aqara Temperature and Humidity ",
        "4/57/65531": [
          1,
          2,
          3,
          5,
          7,
          8,
          9,
          10,
          15,
          12,
          13,
          17,
          18,
          65528,
          65529,
          65531,
          65532,
          65533
        ],
        "4/57/8": "0001",
        "4/57/13": "https://www.aqara.com/en/products.html",
        "4/57/65533": 1,
        "4/57/9": 3,
        "4/57/1": "Aqara",
        "4/57/10": "0003",
        "4/57/7": 1,
        "4/46/65528": [],
        "4/46/65532": 0,
        "4/46/0": [
          4
        ],
        "4/46/65531": [
          0,
          65528,
          65529,
          65531,
          65532,
          65533
        ],
        "4/46/65529": [],
        "4/46/65533": 1,
        "4/29/65528": [],
        "4/29/65533": 1,
        "4/29/1": [
          29,
          57,
          46,
          47
        ],
        "4/29/0": [
          {
            "deviceType": 19,
            "revision": 1
          },
          {
            "deviceType": 17,
            "revision": 1
          }
        ],
        "4/29/3": [
          5,
          6
        ],
        "4/29/65531": [
          0,
          1,
          2,
          3,
          65528,
          65529,
          65531,
          65532,
          65533
        ],
        "4/29/2": [],
        "4/29/65529": [],
        "5/3/65533": 4,
        "5/3/0": 0,
        "5/3/65528": [],
        "5/3/1": 2,
        "5/3/65531": [
          0,
          1,
          65528,
          65529,
          65531,
          65532,
          65533
        ]
```

**Comment by marcelveldt** [comment]
Hmm, this should to be a composed device but it isnt. 
What device is this ? Some zigbee sensor ?

**Comment by lboue** [comment]
Yes this an Aqara AS008 Temperature and Humidity sensor.

**Comment by marcelveldt** [comment]
If you re-pair the device with the Hub, this issue should resolve itself.
Also, we'll introduce a way to re-interview a node from the UI in one of the next versions so you can just us ethat instead of re-pairing. Only a re-pair of the device to the Hub is sufficient, no need to re-commission the hub to HA
