### ISSUE TITLE
Devices fail to be detected as online and reconnect to matter server after downtime

### ISSUE THREAD

**Issue by nalin29** [home-assistant-libs/python-matter-server#354]
I have 4 wifi based matter bulbs. They are frequently shut off and disconnected from the network. Once they are turned back on after a some period of time off both Apple Homekit and Alexa pick up the light within 1 minute of turning on. Home Assistant was able to commission the bulbs and control them but fails to reconnect with them timely or at all after being shut off.

# Env

HA 2023.7.1
Supervisor 2023.07.1
OS 10.3
Matter Server 4.8.2

HA was attempted running in a proxmox vm and on bare metal

# Logs

[core_matter_server_2023-07-08T16-17-54.124Z.log](https://github.com/home-assistant-libs/python-matter-server/files/11991112/core_matter_server_2023-07-08T16-17-54.124Z.log)

I have packet captures of both another pc on the network and from within the matter-server container which show that ipv6 multicast is making to that container from the network and matter devices.

**Comment by nalin29** [comment]
Packet Capture on Matter Server Container showing matter devices

![image](https://github.com/home-assistant-libs/python-matter-server/assets/22562731/b4d5a50b-dca1-42db-959e-c2a55005495b)

**Comment by nalin29** [comment]
![image](https://github.com/home-assistant-libs/python-matter-server/assets/22562731/5851da53-082d-4eb1-a6d4-c69f6b825eca)

This is a MDNS query response from the matter device from the tcpdump from within the matter container. The record contains the fabric id "40C860D460252C7F-..." and matches the node id in the matter server logs. So I do believe that the matter server should be parsing the mdns packet and then attempting to connect to the node with no regard to the resubscribe timeout. But it fails to do so?

**Comment by nalin29** [comment]
[matter-multicast.zip](https://github.com/home-assistant-libs/python-matter-server/files/12004499/matter-multicast.zip)

Filtered Packet Capture to only show multicast packets and fit in the github upload requirements

**Comment by marcelveldt** [comment]
Thanks for the extensive reports. We are looking into this!

**Comment by marcelveldt** [comment]
I could reproduce the issue where devices are turned off at startup of the matter server and then not come back online.
What I could not reproduce is a device that is turned off (so become unavailable) while the matter server is running (and so the subscription set-up) and turned off after some time but maybe I did not wait long enough. I unplugged a device for several hours and as soon as I plugged it back in, within a few seconds the connection was restored, so working as expected.

**Comment by nalin29** [comment]
That is a bit concerning I have tried with the bulbs on and then starting the matter server and bulbs off then starting the matter server. I did take a look at the logs to try to time my tests during the between the re-subscription retries and that would almost always fail. It can be a little random but looking at the packet captures during my test where it did fail  I believe that the matter server does indeed receive the mdns broadcast when the bulbs come back online reliably.

**Comment by marcelveldt** [comment]
bulbs off and then starting matter server was an issue, I fixed that one.

bulbs on and then to off while already started is hard to reproduce but I can see it takes a long time to reinstate if they were offline for a long time

**Comment by nalin29** [comment]
I think I can reproduce this even in a short time period by just waiting to turn them on between re-subscriptions checks this window can be short i think an hour off is no more than 5-10 minutes but after a day its an hour long at least. Try seeing if you can reproduce this by turning the device on when matter-server is not checking for re-subscription.

**Comment by marcelveldt** [comment]
> I think I can reproduce this even in a short time period by just waiting to turn them on between re-subscriptions checks this window can be short i think an hour off is no more than 5-10 minutes but after a day its an hour long at least. Try seeing if you can reproduce this by turning the device on when matter-server is not checking for re-subscription.

Yes I have noticed that too, it keeps on increasing the interval and I've asked the SDK devs if that is intended.
I was thinking that we could also fallback to the poll behavior after x period of time. So use the builtin resubscription until X time has passed and then skip to the 5 minute poll interval. The log will be spawned with errors every 5 minutes but at least it will reconnect.

**Comment by marcelveldt** [comment]
Well, actually it will soon be resolved

https://github.com/project-chip/connectedhomeip/pull/26718
