### ISSUE TITLE
compose.yml: pull access denied for matter-server

### ISSUE THREAD

**Issue by wasnertobias** [home-assistant-libs/python-matter-server#366]
Tried to use the provided [compose.yml](https://github.com/home-assistant-libs/python-matter-server/blob/main/compose.yml) in this repo. Got the following error:
>  ✘ matter-server Error                                                     1.5s 
> Error response from daemon: pull access denied for matter-server, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by marcelveldt** [comment]
@wasnertobias thanks for the report. Turns out the compose file was wrong and you were the first one to discover ;-)
We've fixed the mistake and it should now work
