### ISSUE TITLE
On/off Light Switch device type support

### ISSUE THREAD

**Issue by Gonta01** [home-assistant-libs/python-matter-server#371]
After on/off light switch implemented on ESP32C3 is connected to Home Assistant there are no any entities.
![image](https://github.com/home-assistant-libs/python-matter-server/assets/127857320/1469042e-8fee-4f9b-aaef-67ee71747a28)

By the way, does the ability of device binding (device to device interaction without hub) is supported in Matter integration?

**Comment by marcelveldt** [comment]
Your are probably missing one of the mandatory clusters and/or attributes in that case.
Did you set the devicetype correctly ?

**Comment by marcelveldt** [comment]
Device bindings are not supported

**Comment by Gonta01** [comment]
Thank you for quick response!
