### ISSUE TITLE
Wrong example for sending a command

### ISSUE THREAD

**Issue by farshidtz** [home-assistant-libs/python-matter-server#384]
I find it hard to make sense of the example given for sending a command:

https://github.com/home-assistant-libs/python-matter-server/blob/dd6acaa819326a30ecb13c6069a7df6508a1edcc/README.md?plain=1#L270-L280

Are the message ID and command values correct? Endpoint and node ID values reference some missing code. Is the given dictionary meant to be a JSON example, outside the Python code?
How will the controller know which cluster command is being executed? In the given example, `payload` will be an empty object.

**Comment by farshidtz** [comment]
The JSON object for the `On` command should be, for example:
```json
{
    "message_id": "4",
    "command": "device_command",
    "args": {
      "endpoint_id": 1,
      "node_id": 1,
      "payload": {},
      "cluster_id": 6,
      "command_name": "On"
    }
}
```

**Comment by marcelveldt** [comment]
You can have a look at the included client for a reference implementation, together with Home Assistant.
