### ISSUE TITLE
Subscribing to attribute updated events

### ISSUE THREAD

**Issue by skison** [home-assistant-libs/python-matter-server#386]
I'm working on a custom Python client implementation that needs to be able to subscribe to attribute update events only for a specific attribute; I'm using the `client.py` example client as a reference, but I can't seem to get this functionality working as intended using the newer subscription logic instead of the older 'listen to everything' approach.

From `client.py`, I removed the `START_LISTENING` command and instead replaced it with a `GET_NODES` command to populate the initial state, and followed that up with this:

```
self.subscribe_events(
    self.attribute_updated_callback,
    EventType.ATTRIBUTE_UPDATED,
    )
    await self.subscribe_attribute(2, "1/513/17")
    await self.subscribe_attribute(2, "1/513/18")
```

To give some additional context, I created a simple callback method within `MatterClient`:
```
def attribute_updated_callback(self, event, data):
    print(event, data)
```

This callback function is never invoked, and the client itself never receives a message once an attribute update event occurs.

I can also confirm that the attributes I'm listening for do exist (they map to a real thermostat's setpoints), and do show up on my other client that is still using the start_listening command:
`{ "event": "attribute_updated", "data": [2, "1/513/17", 2222] }`
`{ "event": "attribute_updated", "data": [2, "1/513/18", 2222] }`
These messages do show up on the server end for the client using start_listening, but not for the subscription-only client. So it seems that these attribute update events are only being handled for clients using start_listening, and not for other clients that are subscription-only.

Is this an intended operation of the server code, or have I gone about implementing this incorrectly? If there is an example of a client Python code that subscribes to attribute updates in this way, please let me know!

**Comment by skison** [comment]
I'm on release 3.7.0 by the way.

**Comment by marcelveldt** [comment]
Sorry for the late reply. For a reference implementation (including the subscription logic), take a look at Home Assistant as we created this library/server primary to be used in our Home Assistant project.

And yes, you NEED to call "start_listening" before you get any event callbacks at all.

**Comment by skison** [comment]
Thank you for the clarification! Earlier I poked through the codebase a bit to see how that listening function was structured, and it does make more sense now (I think I was thrown off initially by some of the wording in the readme).

Keep up the good work!

**Comment by marcelveldt** [comment]
OK, good to hear, let me know if you have any more questions.
