### ISSUE TITLE
setup_pin_code should be a string

### ISSUE THREAD

**Issue by sammachin** [home-assistant-libs/python-matter-server#408]
The payload for on network commissioning expects the value of the setup_pin_code as a number/int
eg
```
{"message_id":"2","command":"commission_on_network","args":{"setup_pin_code":21036639901}}
```

However its possible and likely that the manual pairing code for a device will start with a leading zero but it will always be a fixed length. Many JSON libraries either refuse to allow a number value to start with a zero or they drop the leading zero.

Therefore it would be better to make this value a string to allow for codes that start with a zero

```
{"message_id":"2","command":"commission_on_network","args":{"setup_pin_code":"04970012338"}}
```

**Comment by marcelveldt** [comment]
Valid point/suggestion but we do not want to derive from the specs/SDK here, where an integer is required, so imo perfectly fine to just send the code without the leading zero.

You may want to take this complaint upstream if you really want and submit an issue report in the project-chip repo ?

**Comment by sammachin** [comment]
Do you know where the SDK expects an int?
The matter spec just says that the manual pairing code is encoded as an 11 or 21 digit decimal *numeric string* though not an integer

Also if you drop the leading zero then the check digit calculation fails.

**Comment by marcelveldt** [comment]
https://github.com/project-chip/connectedhomeip/blob/master/src/controller/python/chip/ChipDeviceCtrl.py#L1690

Did you verify that the share code ever starts with a leading zero ?
Regular commission codes are strings and can actually start with a zero but so far I've not seen a share code starting with a zero.

**Comment by sammachin** [comment]
yes I've had several codes starting with a zero.

The pairing code will start with a zero if the VID and PID are not sent (because its not a custom flow which on-network commissioning will always be) and the discriminator is less than 1023
Assuming a random distribution of discriminator values the (0-4095) then its about a 1 in 4 chance that the code will start with a 0

**Comment by marcelveldt** [comment]
Hmmm, interesting. In that case there is a bug in the SDK itself then as that accepts an integer only (or the type hint is wrong, something we've seen before). It should be fixed upstream in that case. I've asked this on the CSA slack just now to confirm, I'll get back to you on this one asap.

**Comment by marcelveldt** [comment]
OK, as we've just discussed by chat, we should remove the "commission_on_network" from the public API as there is no actual need/use for it and at all times the "commission_with_code" should be used which is universal and handles all situations already managed in the sdk.
