### ISSUE TITLE
Issues using matter 5.0 with ha 2023.11.3

### ISSUE THREAD

**Issue by jtenniswood** [home-assistant-libs/python-matter-server#442]
I get an error saying 'The Matter server is not the correct version'
If I roll back to the previous version it works fine.

<img width="707" alt="Screenshot 2023-11-30 at 19 54 45" src="https://github.com/home-assistant-libs/python-matter-server/assets/10881541/c3655785-cd93-4694-8017-7843273718bd">

<img width="441" alt="Screenshot 2023-11-30 at 19 54 53" src="https://github.com/home-assistant-libs/python-matter-server/assets/10881541/2bc8a868-8433-48a0-855c-f9bac7d897a7">

<img width="620" alt="Screenshot 2023-11-30 at 19 55 11" src="https://github.com/home-assistant-libs/python-matter-server/assets/10881541/8a0eb671-2acc-4e03-b2b4-9aae66125c41">

**Comment by Scope666** [comment]
Exact same here, rolled back to v4 for now.

**Comment by jtenniswood** [comment]
Then maybe this shouldn't have been released under the stable tag, until
the release was public.

**Comment by marcelveldt** [comment]
You shouldn't be auto updating your containers and not expect things to never break ;-)

The Home Assistant docker image that is published is aimed at the Home Assistant add-on the ONLY officially supported way of running matter with Home Assistant. Running it yourself in docker is completely at your own risk and administration. In this case I did mention that the Matter server 5.0.0 is targeted at HA 2023.12.

**Comment by brianegge** [comment]
I'm running HA 2024.1. Which Matter Server version do I run? How do I tell? I don't see it in the release notes. I don't see anything in the GUI saying which version is required. I guess I will continue to run v4.0.2 until it breaks, or I get a new Matter device which requires a newer Matter server.
