### ISSUE TITLE
Command to pair with <pin_code> <discriminator>?

### ISSUE THREAD

**Issue by olavt** [home-assistant-libs/python-matter-server#443]
What is the command to perform this pairing command?

`chip-tool pairing ble-wifi <node_id> <ssid> <password> <pin_code> <discriminator>`

I have successfully used this command with the QR-code:

{
  "message_id": "2",
  "command": "commission_with_code",
  "args": {
    "code": "MT:Y.ABCDEFG123456789"
  }
}

**Comment by olavt** [comment]
On workaround is to generate a pairing code in a format that is supported by Matter Server:

// Generates the short manual pairing code (11-digit).
chip-tool payload generate-manualcode \
  --discriminator 3840 \
  --setup-pin-code 20202021 \
  --version 0 \
  --commissioning-mode 0

**Comment by marcelveldt** [comment]
commission_with_code takes both a QR-code like string or a pincode/sharing code.
If you want to filter a sharing/pin code by discriminator you will indeed have to generate the qr code like you shows above but in normal circumstances that would not be needed as chances are small that multiple devices with the exact same code are in commissionable mode at the exact same time on the same network.
