### ISSUE TITLE
Why don't include a message type on all messages received?

### ISSUE THREAD

**Issue by olavt** [home-assistant-libs/python-matter-server#452]
It would be a lot easier to consume the messages received from the Matter Server if each message received over the web socket contained a message type.

Is the pattern expected that one sends a command and waits for a reply, or can one send a bunch of commands and process the messages independently? I would like to do the latter from a c# program, but then it's a little bit messy to have to figure out what kind of SuccessResultMessage one is dealing with. A message type field would be convenient.

**Comment by marcelveldt** [comment]
You may want to check out our reference client implementation. We use an RPC-like pattern where you send a message ID with each command and you get the result back with that same message ID. Just make sure to send a unique message id with each command

**Comment by olavt** [comment]
I have it working now. I guess it's up to the client if it wants to wait for the response just after sending, or if the client is happy to process the responses "out-of-band".
