### ISSUE TITLE
Where is state for the server stored?

### ISSUE THREAD

**Issue by olavt** [home-assistant-libs/python-matter-server#455]
Is all state related to running the Python Matter Server stored on the /data:/data volume?

If I want to move the container to another Raspberry Pi, can I just copy the files in the data volume over and start the Python Matter Server on the other machine?

What if I wanted to run the chip-tool against the same Matter Fabric? How do I transfer the state from the Matter Server to where I want to run chip-tool?

**Comment by marcelveldt** [comment]
yeah, theoretically but why ? 
Note that you would then point it at the same storage location (/data), use the same fabric and vendor id's etc.

**Comment by olavt** [comment]
It could be interesting to run the chip-tool directly against the Matter Fabric for troubleshooting / testing and not having to go through the web socket interface of the Matter Server for everything.

**Comment by olavt** [comment]
I have tested the transfer of a Matter Server from one Raspberry Pi to another and it works simply by copying the content of the data directory over and starting the docker container on the new host.

It would be nice to know how to transfer credentials over to chip-tool as well.

**Comment by olavt** [comment]
I have investigated this a bit more and the appropriate way to run chip-tool against the Python Matter Server nodes would maybe be to use the Matter Multi-Admin features.
