### ISSUE TITLE
Possibility to specify network interface

### ISSUE THREAD

**Issue by testuser7** [home-assistant-libs/python-matter-server#459]
Please add an option to specify the network interface to use.

**Comment by testuser7** [comment]
> Isn't it just connected to the host network and is using whatever network interface you configured there?

This is currently how it is implemented. But not everyone may want to use all interfaces.

**Comment by marcelveldt** [comment]
It's an sdk limitation which just picks all interfaces. For the HA add-on we're planning on switching to macvlan at some point and no longer forward the entire host networking.
