### ISSUE TITLE
no matching manifest for linux/arm/v7 in the manifest list entries.

### ISSUE THREAD

**Issue by StevenKRT** [home-assistant-libs/python-matter-server#465]
I have this error in regular installation, can you fix it?
docker: no matching manifest for linux/arm/v7 in the manifest list entries.

**Comment by agners** [comment]
Currently, Python wheels for the Matter SDK (which this implementation is built on) for 32-bit Arm are not supported by the Matter SDK itself. I don't expect that this will change. :cry: 

You have to migrate to a 64-bit installation to use our Matter Server (either aarch64 or x86-64).
