### ISSUE TITLE
Reliability regression from 5.0.1 to stable

### ISSUE THREAD

**Issue by Xploder** [home-assistant-libs/python-matter-server#476]
Hey,
this one took a while to figure out.

I've tried matter together with a ESP32 example firmware (so just WiFi) as an UnRAID Docker.
While everything worked fine when adding the device to Alexa and there were absolutely no reliability issues, when adding it to Home-Assistant using the latest stable version I get a super unstable experience after just a couple of seconds. Because of the finnicky IPV6 setup I've first started trying different Hosts, so I've spun up the docker on multiple other host machines (Arch VM, UbuntuServer VM, Raspberry Pi 3 running Raspbian 12) with the same outcome. 

This was with current stable and the version before that.

It was when I tried HAOS on a VM when it started working and I thought it had something to do with kernel/networkmanager patches in this distribution. Turns out the HAOS addon was still using an older version 5.0.1. 

So I've tried this version on one of the other hosts and it worked! Guess there has been a regression somewhere in between?! I'd love to help troubleshoot this.

Logs with current stable:
https://pastebin.com/EAFpB0z4

Logs with 5.0.1
https://pastebin.com/mVy5g8rU

**Comment by Xploder** [comment]
Can confirm that 5.0.3 works aswell.

**Comment by marcelveldt** [comment]
5.0.1 was a very flaky version which we should have fixed with 5.0.3.
Can you please also test with version 5.1.2. please ?

**Comment by Xploder** [comment]
Hey Marcel,
my "stable version" logs from the original post are from version 5.1.1.

Best regards

**Comment by marcelveldt** [comment]
I can reproduce the situation here, I'm looking at a fix.
