### ISSUE TITLE
deps: home-assistant-chip-core declared as an optional dependency

### ISSUE THREAD

**Issue by THETCR** [home-assistant-libs/python-matter-server#484]
`home-assistant-chip-core` is explicitly required, but it is declared as an optional dependency.
All dependencies that are explicitly required should be declared as production dependencies.

**Comment by MartinHjelmare** [comment]
`home-assistant-chip-core` is only required for the server and not for the client. Has that changed?

**Comment by marcelveldt** [comment]
home-assistant-chip-core is only required for the server.
