### ISSUE TITLE
Create docker image for testing

### ISSUE THREAD

**Issue by mhanuel26** [home-assistant-libs/python-matter-server#491]
I am not sure how to create the docker image to setup the server on my ubuntu x86 platforkm, I have tried the following but it is not working for me, can you advice please 

![image](https://github.com/home-assistant-libs/python-matter-server/assets/2257779/9ca1810e-3852-4162-b72b-bd7be4434986)

**Comment by MartinHjelmare** [comment]
If you're going to use the docker image for development I recommend the `Dockerfile.dev` docker file.

If you're going to build from the `Dockerfile` file, you need to provide an argument for  `PYTHON_MATTER_SERVER`.
