### ISSUE TITLE
Docker container immediately restarts

### ISSUE THREAD

**Issue by tymm** [home-assistant-libs/python-matter-server#492]
I'm trying to get the python-matter-server to run on my Raspberry Pi 4B with the following command:
```
docker run -d --name matter-server --restart=unless-stopped -v ./data:/data -v /run/dbus:/run/dbus:ro --network=host --platform linux/arm64/v8 ghcr.io/home-assistant-libs/python-matter-server:stable
```

It seems to fail immediately without any output.

I suspect that the `--platform linux/arm64/v8` could be the culprit.
However without it, I get the following warning with the same immediately failing container:
`WARNING: The requested image's platform (linux/arm64) does not match the detected host platform (linux/arm/v8) and no specific platform was requested`

```
pi@server:~ $ uname -a
Linux server 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
```

**Comment by karlshea** [comment]
Have you tried removing the `/v8` and just passing `--platform linux/arm64`?

**Comment by marcelveldt** [comment]
Like explained by @karlshea you need a 64 bit OS to run the Matter docker container.
Also if you are planning to use Thread based matter devices, that wont work reliable our of the box. We tweaked Home Assistant OS to handle it, you will have to do it yourself. See instructions in the readme. In general its not recommended to run your own OS with Matter server unless you really know what you're doing.

**Comment by tymm** [comment]
@marcelveldt @karlshea I'm pretty sure that I'm running the 64bit version of Raspbian.

```
pi@server:~ $ uname -a
Linux server 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux

pi@server:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

**Comment by karlshea** [comment]
Some Raspberry Pi OS versions had a weird situation where the kernel was 64-bit but userspace was 32-bit. If you're getting "does not match the detected host platform (linux/**arm**/v8)" I suspect that's what's going on with your system.

```
# docker system info
...
 OSType: linux
 Architecture: aarch64
...
```

Also try these:

```
root@ns2-pi:~# arch
aarch64
root@ns2-pi:~# dpkg --print-architecture
arm64
root@ns2-pi:~# file /lib/systemd/systemd
/lib/systemd/systemd: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, BuildID[sha1]=4b2dc663473cee025329775bd36852659f0a1c1f, for GNU/Linux 3.7.0, stripped
```

**Comment by torablien** [comment]
@karlshea I am running into the same issue and think it may be as you say where 
> the kernel was 64-bit but userspace was 32-bit. 

What version are you running where you have it working? Any suggested workarounds short of wiping and reinstalling?

```
$ uname -m
aarch64
```

```
$ dpkg --print-architecture
armhf
```

```
$ file /lib/systemd/systemd
/lib/systemd/systemd: ELF 32-bit LSB pie executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, BuildID[sha1]=c8e472c9a12568fbde5035980497ffc8e4a857cd, for GNU/Linux 3.2.0, stripped
```


```
$ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

```
$ cat /etc/apt/sources.list.d/docker.list
deb [arch=armhf signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/raspbian bullseye stable
```

```
$ docker version
Client: Docker Engine - Community
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:08:26 2023
 OS/Arch:           linux/arm
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:08:26 2023
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.6.26
  GitCommit:        3dd1e886e55dd695541fdcd67420c2888645a495
 runc:
  Version:          1.1.10
  GitCommit:        v1.1.10-0-g18a0cb0
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

```
$ docker system info
 ...
 Kernel Version: 6.1.21-v8+
 Operating System: Raspbian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 3.705GiB
 ...
```

**Comment by tymm** [comment]
@karlshea Thanks. That explains my situation.

**Comment by torablien** [comment]
Installing on the [64-bit version of Raspbian Bullseye](https://www.raspberrypi.com/software/operating-systems/#:~:text=Archive-,Raspberry%20Pi%20OS%20(Legacy%2C%2064%2Dbit),-Compatible%20with%3A) seems to have fixed the issue for me.

**Comment by karlshea** [comment]
Just FYI they suggest wiping to upgrade to Bookworm so if you're wiping anyways should maybe make the jump now.

**Comment by torablien** [comment]
> Just FYI they suggest wiping to upgrade to Bookworm so if you're wiping anyways should maybe make the jump now.

It seems like different functionality is still being added to Bookworm (outside of HA) so I'm waiting until it's more mature before upgrading. Is there anything I'm missing by sticking with bullseye?

**Comment by karlshea** [comment]
Mine is headless so I don't know about anything on the desktop side, the biggest thing I like about Bookworm is they moved to NetworkManager so that made some things easier around adding additional IPs and things. Other than that nothing too big.
