### ISSUE TITLE
Primary Ethernet Interface

### ISSUE THREAD

**Issue by Mermarky** [home-assistant-libs/python-matter-server#493]
How do you point server to the correct primary ethernet interface? Is there an environment variable?
I believe my primary ethernet interface should be ovs_eth0 (see below)

----- log entry from the matter server------
[1704644893.467904][1:1] CHIP:DL: Got Ethernet interface: eth1
[1704644893.468045][1:1] CHIP:DL: Found the primary Ethernet interface:eth1
------END-------------------------------

-------- "ip a" result---------
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1
    link/sit 0.0.0.0 brd 0.0.0.0
3: eth1: <NO-CARRIER,BROADCAST,MULTICAST,SLAVE,UP> mtu 1500 qdisc pfifo_fast master ovs-system state DOWN group default qlen 1000
    link/ether 00:XX:XX:XX:XX:b4 brd ff:ff:ff:ff:ff:ff
4: eth0: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master ovs-system state UP group default qlen 1000
    link/ether 00:XX:XX:XX:XX:b3 brd ff:ff:ff:ff:ff:ff
5: eth0.10: <NO-CARRIER,BROADCAST,MULTICAST,MASTER,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether ea:XX:XX:XX:XX:78 brd ff:ff:ff:ff:ff:ff
6: ovs-system: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1
    link/ether be:XX:XX:XX:XX:87 brd ff:ff:ff:ff:ff:ff
7: ovs_eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1
    link/ether 00:XX:XX:XX:XX:b3 brd ff:ff:ff:ff:ff:ff
    inet 192.168.X.X/24 brd 192.168.X.255 scope global ovs_eth0
       valid_lft forever preferred_lft forever
    inet6 2603:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:a6b3/64 scope global dynamic mngtmpaddr 
       valid_lft 86318sec preferred_lft 86318sec
    inet6 fe80::XXXX:XXXX:XXXX:XXb3/64 scope link 
       valid_lft forever preferred_lft forever

**Comment by Mermarky** [comment]
Well... the answer is in my question 
 BACKBONE_IF: "ovs_eth0" is the answer

**Comment by agners** [comment]
It doesn't seem that there is a way to control which Ethernet interface the code should consider as primary.  From looking at the code the "Found the primary Ethernet interface:" string comes from the diagnostics provider, which is only relevant if the SDK would be running as a device, see:

https://github.com/project-chip/connectedhomeip/blob/v1.2.0.1/src/platform/Linux/DiagnosticDataProviderImpl.cpp#L96

So this should not be relevant when running as a controller.
