### ISSUE TITLE
Problem with old node data re-appearing after restart?

### ISSUE THREAD

**Issue by olavt** [home-assistant-libs/python-matter-server#496]
I think there is some kind of bug related to saving node data (from interview).

I'm developing a Matter end device and in the process I removed endpoint 6 for the device after it was added to the Python Matter Server.

Then I sent the "interview_node" command to get the node information (attributes) updated in the Python Matter Server.

When I connect to the Python Matter Server, I see that the node information is correct.

Then I re-started the Python Matter Server.

When I now connect to it, I get the information about the endpoint that was deleted again.

Here's a snippet from the messages:

After "interview_node":

        "5/1037/0": 703.0,
        "5/1037/65532": 63,
        "5/1037/65533": 3,
        "5/1037/65528": [],
        "5/1037/65529": [],
        "5/1037/65531": [
          0,
          65528,
          65529,
          65531,
          65532,
          65533
        ]
      },
      "attribute_subscriptions": [
        [
          3,
          1024,
          0
        ],
        [
          5,
          1037,
          0
        ],
        [
          1,
          1026,
          0
        ],
        [
          4,
          1027,
          0
        ],
        [
          6,
          1026,
          0
        ],
        [
          2,
          1029,
          0
        ]
      ]
    }
  ]
}

After re-starting the server:

        "5/1037/0": 701.0,
        "5/1037/65532": null,
        "5/1037/65533": 3,
        "5/1037/65528": [],
        "5/1037/65529": [],
        "5/1037/65531": [
          0,
          65528,
          65529,
          65531,
          65532,
          65533
        ],
        "6/3/65528": [],
        "6/3/65529": [],
        "6/3/65531": [
          65528,
          65529,
          65531
        ],
        "6/4/65528": [],
        "6/4/65529": [],
        "6/4/65531": [
          65528,
          65529,
          65531
        ],
        "6/29/65528": [],
        "6/29/65529": [],
        "6/29/65531": [
          65528,
          65529,
          65531
        ],
        "6/1026/65528": [],
        "6/1026/65529": [],
        "6/1026/65531": [
          65528,
          65529,
          65531
        ],
        "6/1026/0": null
      },
      "attribute_subscriptions": [
        [
          3,
          1024,
          0
        ],
        [
          5,
          1037,
          0
        ],
        [
          1,
          1026,
          0
        ],
        [
          4,
          1027,
          0
        ],
        [
          6,
          1026,
          0
        ],
        [
          2,
          1029,
          0
        ]
      ]
    }
  ]
}

**Comment by marcelveldt** [comment]
Good catch, I will look at this on monday.
