### ISSUE TITLE
Should be able to specify node id when commissioning device

### ISSUE THREAD

**Issue by olavt** [home-assistant-libs/python-matter-server#502]
It would be useful to be able to specify a node id when commissioning a device rather than being assigned one. Getting a node id could be the default behavior if one doesn't specify a node id.

In some cases one might need to re-build something it would be nice to be able to re-create the devices with specified node id's in order to avoid needing to re-mapping the node id's.

**Comment by marcelveldt** [comment]
node id is internal and should actually be completely random. You should not match any logic on it.
In fact we have it now lineair counting for the time being because it helps us debugging but at some point we'll follow everyone else and just make it randomized number.

**Comment by olavt** [comment]
The Matter plattforms allow for assigning node id's.

**Comment by olavt** [comment]
@marcelveldt Could we re-visit this issue?

I would appreciate if it would be possible to specify a node id in the "commission_with_code" command.

If a node id is not specified you can pick a random node id or whatever, but if it's specified you should use it. If it's already used, just return an error.

I don't see why it should not be possible to specify it as long as the platform is designed around it.

**Comment by marcelveldt** [comment]
Sorry no because we are linear counting and this change would have other impact.
We need to guarantee that we send a node id that has never been used before and that is guarded now. Allowing a node id in the commission command lifts that guard and can have bad side effects. So no, sorry.

**Comment by olavt** [comment]
Could this be reconsidered? I think it should be possible to replace a node devive without having to re-map the node id.

**Comment by olavt** [comment]
@marcelveldt Couldn't the logic be changed as follows:

If a NodeId is not specified, use the lowest available free NodeId.

If a NodeId is specified, try to add it to the Fabric. If the SDK returns an error indication that the NodeId is in use, return an error, otherwise go ahead and use it.
