### ISSUE TITLE
The problem with launching the integration

### ISSUE THREAD

**Issue by RykovDC** [home-assistant-libs/python-matter-server#505]
After upgrading to version 5.2.1, the integration stopped running

**Comment by RykovDC** [comment]
![image](https://github.com/home-assistant-libs/python-matter-server/assets/139807719/e9302077-0403-4905-8098-382462108aed)
![image](https://github.com/home-assistant-libs/python-matter-server/assets/139807719/c14933eb-39a6-4f25-ad89-76486c46f00f)

**Comment by marcelveldt** [comment]
@agners FYI

**Comment by marcelveldt** [comment]
Temporary solution: enable the beta toggle in the add-on settings.

**Comment by RykovDC** [comment]
> @agners FYI

Explain to the beginner what it is?

**Comment by danielBreitlauch** [comment]
same issue here.

**Comment by marcelveldt** [comment]
> > @agners FYI
> 
> Explain to the beginner what it is?

I was pinging a coworker about the issue.

**Comment by marcelveldt** [comment]
Please no "same here" comments, thanks!

We are ware of the issue and will provide a new addon bump soon.

**Temporary solution: enable the beta toggle in the add-on settings.**
