### ISSUE TITLE
Max re-subscribing interval?

### ISSUE THREAD

**Issue by olavt** [home-assistant-libs/python-matter-server#506]
Is there a maximum re-subscribing interval used? It was not obvious to me looking at the source code.

2024-01-21 10:11:46 matter-server chip.DMG[1] ERROR Failed to establish CASE for re-subscription with error 'src/protocols/secure_channel/CASESession.cpp:553: CHIP Error 0x00000032: Timeout'
2024-01-21 10:11:46 matter-server matter_server.server.device_controller.[node 4][1] INFO Previous subscription failed with Error: 50, re-subscribing in 2222147 ms...

The above is a wait for 37 minutes and if the next attempt results in even a longer retry interval, it could start to get painful.

In the code it looks like this is the setup for the interval:

            node_logger.info("Setting up attributes and events subscription.")
            interval_floor = 0
            interval_ceiling = (
                random.randint(60, 300) if battery_powered else random.randint(30, 120)
            )

What are the units for these numbers? Seconds / Minutes?

Are these the numbers used as a based for the "re-subscribing in X ms"?

**Comment by marcelveldt** [comment]
we are currently relying on the sdk for resubscriptions but it does not have a good implementation for operational node discovery. So in case of an offline node it starts polling and increases the interval to insane heights.

We are going to change this behavior soon and do our own mdns discovery of operational nodes.
Until then: do not power off matter nodes ;-)
