### ISSUE TITLE
Nanoleaf Essentials thread lightbulbs can no longer be controlled by GH after being added to Matter through HA

### ISSUE THREAD

**Issue by kent30at** [home-assistant-libs/python-matter-server#507]
As the title says, I added 5 lights to Home Assistant through the companion app. These lightbulbs have been previously paired with my google home (3 Thread BR) and have been working fine. After adding them to Matter through app, they seem to work fine through both apps for a few minutes. However, 10 minutes in and all of the lights added to Home Assistant can only be interacted with through Home Assistant. Any attempt to control them through Google Home does not work, however it can read the current status of the light. 

Currently running core- 2024.1.5 and Frontend - 20240104.0

HA and Matter are running in docker containers and installed as per the instructions on the github page. I understand that it is recommended to use HAOS, but that is not currently an option for me.

**Comment by kent30at** [comment]
I am currently testing to see if the hand-off failure is due to having a Home Assistant service linked in the google home app. I will close the comment if this resolves in the issue.

**Comment by marcelveldt** [comment]
1) This is not for support. Use discord or forums to seek support. 
2) You are running in docker, this is not supported and completely at your own risk.
