### ISSUE TITLE
Frequency of updates for a subscription?

### ISSUE THREAD

**Issue by olavt** [home-assistant-libs/python-matter-server#513]
What is controlling how often the client receives updates to attributes after setting up a subscription (using the "subscribe_attribute" command)?

I have a need to be able to receive updates from a Matter Accessory Devices as often as every 2.5 seconds.

The above example is receiving the current power consumption for an electric energy service device (household meter).

**Comment by marcelveldt** [comment]
the client device defines how often it sends attribute changes. all we do is define a floor and ceiling.
We set the floor to 0 seconds (so as soon as possible) and the ceiling depends on of the device is battery powered or not but is a rather high value of a few minutes to detect if the device is still alive. Within those limits the device sends attribute updates as soon as it wants

**Comment by olavt** [comment]
Ok, so if I understand it correctly a Matter Accessory Device updating the attribute will immediately be picked up by the Python Matter Server and then sent over the web socket to the client?

What happens if I have a device not sending any attribute updates for a long time? That could happen with a lot of devices (like movement sensors)?

**Comment by marcelveldt** [comment]
> Ok, so if I understand it correctly a Matter Accessory Device updating the attribute will immediately be picked up by the Python Matter Server and then sent over the web socket to the client?

YES

> I haven't looked closely, but to mee it seemed that updates from several devices where sent to the client at the same time (like every minute). But,, I need to test this more.

Some devices are flaky. For example I've seen matter bridges that jus send all attributes at every ceiling interval (so every minute). In fact I've added some code today to filter out those redundant messages.

> What happens if I have a device not sending any attribute updates for a long time? That could happen with a lot of devices (like movement sensors)?

If a device misses its interval ceiling repot interval, it gets marked as offline and polled for status until its back again.
So as long as a device is still working, it will send updates at each interval. So a battery node such as a motion sensor will wake up at that interval as well to inform the controller(s) that its still there

**Comment by olavt** [comment]
I have tested this and updates are arriving when the Matter Accessory devices are changing attributes. I have tested this with a Smart RGBTW Bulb and when changing color, the updates are arriving quite frequent (multiple messages per second).
