### ISSUE TITLE
Add JSON for example command

### ISSUE THREAD

**Issue by olavt** [home-assistant-libs/python-matter-server#519]
The Readme file contains this example code in Python:

command = clusters.LevelControl.Commands.MoveToLevelWithOnOff(
  level=int(value), # provide a percentage
  transitionTime=0, # in seconds
)

Could  the JSON be added below as an example too?

It would be nice to have the JSON for a bit more complex command with some parameter payload for people not using the Python client.

**Comment by olavt** [comment]
I'm trying to replicate this chip-tool command:

./chip-tool colorcontrol move-to-color 28311 51576 10 0 0 1 1

The command I'm sending is:

{
    "message_id": "8",
    "command": "device_command",
    "args": {
        "node_id": 4,
        "endpoint_id": 1,
        "cluster_id": 768,
        "command_name": "MoveToColor",
        "payload": {
            "currentX": 28311,
            "currentY": 51576,
            "transitionTime": 10,
            "optionsMask": 0,
            "optionsOverride": 0
        }
    }
}

The color of the light bulb is however not set to the same color as the chip-tool command, so I guess I have done some errors in the mapping to JSON.

It would be great to have some samples of similar mappings.

**Comment by olavt** [comment]
The issue in my JSON was that I used currentX and currentY. Correct parameter names are colorX and colorY.

This JSON is working as expected:

{
    "message_id": "8",
    "command": "device_command",
    "args": {
        "node_id": 4,
        "endpoint_id": 1,
        "cluster_id": 768,
        "command_name": "MoveToColor",
        "payload": {
            "colorX": 28311,
            "colorY": 51576,
            "transitionTime": 10,
            "optionsMask": 0,
            "optionsOverride": 0
        }
    }
}

**Comment by marcelveldt** [comment]
We have no interest in expanding the readme for now as it doesn't have our priority but feel free to Pr changes if you see a real need for that.
