### ISSUE TITLE
Commisioning a device already on the network from Home Assistant

### ISSUE THREAD

**Issue by Diegorro98** [home-assistant-libs/python-matter-server#54]
I would like to know it because I have been able to commisionate a device using chip-tool, but as I have home assistant OS in a VM, I can't commisionate the device using bluetooth so by opening the commisioning window with chip-tool and then commisioning it with Home Assistant over the network will allow me to test the matter server.

**Comment by jdesai61** [comment]
This should help

https://community.home-assistant.io/t/matter-in-home-assistant-workshop-announcement/426129/132?u=shukkar

**Comment by Diegorro98** [comment]
I tried, I have been able to commisionate the device using on network pairing with chip-tool (so commisioning on network works), but home assistant can't do the same. From the commisioning logs, I've read that it tries to use ble commisioning, and if it doesn't find a Bluetooth adapter, it fails.

I'm going to change the title of the issue to represent better the problem that exist now.

**Comment by jdesai61** [comment]
I have successfully used home-assistant to commission on-network device. BLE error message inb my case was a red-herring - HA add-on also does IP discovery after BLE fails. However, my success rate on pairing was one in five or less - something likely to do with UDP device discovery.  Double check that you are using a manual pairing code when calling matter_experimental.commission , Do not use the one that starts with MT:

**Comment by Diegorro98** [comment]
Thanks! This workaround (or maybe it isn't a workaround) worked. It works better after restarting the matter server.

**Comment by agners** [comment]
The `MT:` pairing code (QR Code) has a bitfield which says where too look for the device. If you use a QR code which has been generated for Bluetooth commissioning, commissioning won't work.
