### ISSUE TITLE
Responses to read_attribute should be more uniform

### ISSUE THREAD

**Issue by olavt** [home-assistant-libs/python-matter-server#577]
When you read a single attribute like this:

```json
    {
      "message_id": "4",
      "command": "read_attribute",
      "args": {
        "node_id": 1,
        "attribute_path": "0/52/1",
        "fabric_filtered": false
      }
    }
```

The response is not including any attribute path like this:

```json
{
  "message_id": "4",
  "result": 21664
}
```

When you request multiple attributes like this:

```json
  {
    "message_id": "5",
    "command": "read_attribute",
    "args": {
      "node_id": 1,
      "attribute_path": "0/52/*",
      "fabric_filtered": false
    }
  }
```

The response now includes the attribute path for each attribute returned (some attributes left out to shorten):

```json
{
  "message_id": "5",
  "result": {
    "0/52/1": 22192,
    "0/52/2": 16720,
    "0/52/3": 36880,
    "0/52/65532": 1,
    "0/52/65533": 1,
    "0/52/65528": []
  }
}
```

It would be a lot cleaner if the response format would have been identical between these use cases.

Ideally the response from the first command should have been:

```json
{
  "message_id": "4",
  "result": {
    "0/52/1": 22192
  }
}
```

Then one could parse the result without having to make check for the differences in the returned format.

With the current format, I have to do some ugly stuff on the client side like this (C# code):

        public Dictionary<string, dynamic> GetAttributes()
        {
            Dictionary<string, dynamic> attributes;

            // Check if result message is the value for a single attribute or a dictionary with attribute path and values
            try
            {
                attributes = Result.ToObject<Dictionary<string, dynamic>>();
                return attributes;
            }
            catch (Newtonsoft.Json.JsonSerializationException ex)
            {
                // Deserialize to Dictionary<string, dynamic> failed.
                // Assuming it's because Result contains a single attribute value
            }

            // Result contains a single attribute
            attributes = new Dictionary<string, dynamic>();
            string attributePath = _readAttributeCommand.AttributePath;
            attributes.Add(attributePath, Result);

            return attributes;
        }

**Comment by marcelveldt** [comment]
I think we should just split up the function then into a read_attribute and a read_attributes

**Comment by olavt** [comment]
Whatever, just as long as the response format is more consistent. I'm happy with either, but you may never know when 0, 1 or more attributes may get returned. For me it would be most logical to use a single message, which could return a list of zero or more attributes.

**Comment by olavt** [comment]
Just another related question:

Is the use of "*" in the attribnute path ok? I'm not sure if it's documented somewhere. I just did it without thinking too much about it, but I don't think it works with the chip-tool and you need to use special identifiers for the wildcards.

The following wildcards are available:

For all attributes: 0xFFFFFFFF
For all clusters: 0xFFFFFFFF
For all endpoints: 0xFFFF

**Comment by marcelveldt** [comment]
Yes wildcards are perfectly fine and you can even use a standard *

**Comment by olavt** [comment]
Test 5.7.0 and the new uniform return format is working fine!

Thanks for fixing.
