### ISSUE TITLE
Hardware MAC address encoding format?

### ISSUE THREAD

**Issue by olavt** [home-assistant-libs/python-matter-server#580]
I have a Thread device with MAC address 0xe8, 0xf0, 0x00, 0x20, 0x1d, 0xe5, 0x08, 0x08 reported by the chip-tool.

Python Matter Server reports this (in the NetworkInterfaces attribute of the General Diagnostics Cluster):

        "0/51/0": [
          {
            "0": "OpenThread-7239",
            "1": true,
            "2": null,
            "3": null,
            "4": "6PAAIB3lCAg=",
            "5": [],
            "6": [],
            "7": 4
          }
        ]

The attribute with ID 4 (HardwareAddress) is encoded as "6PAAIB3lCAg=".

What is the encoding of this attribute and how do I decode it back to the 8-byte MAC-address?

**Comment by marcelveldt** [comment]
Best thing to do is always check our client implementation as a reference.
In this case: https://github.com/home-assistant-libs/python-matter-server/blob/main/matter_server/client/client.py#L294

**Comment by olavt** [comment]
What does this mean?

"# note that the bytes string can be optionally base64 encoded"

In what cases is it base64 encoded and when is it not?

**Comment by marcelveldt** [comment]
It is base64 encoded if it has been sent over the wire (the json serializer encodes it).
So in your case you're consuming the API, it will be base64 encoded.
