### ISSUE TITLE
Provide functionality for subscribing to events

### ISSUE THREAD

**Issue by olavt** [home-assistant-libs/python-matter-server#586]
As far as I could see there is currently no functionality for subscribing to events.

Are there any plans to add this?

**Comment by marcelveldt** [comment]
You subscribe to node events automatically. Note that currently we only forward urgent events

**Comment by olavt** [comment]
I was thinking about events like these:
- HardwareFaultChange
- NetworkFaultChange
- BootReason

I guess a workaround now is to subscribe to the attributes that may change as a result of these events.

**Comment by marcelveldt** [comment]
Yeah, that is better as the non-urgent events are very verbose

**Comment by olavt** [comment]
I'm a bit confused on how the "attribute_updated" events are currently working.

I found this in the code ():

`        LOGGER.debug(
            "The subscribe_attribute command has been deprecated and will be removed from"
            " a future version. You no longer need to call this to subscribe to attribute changes."
        )`

How can I general subscribe to updates to cluster attributes if I'm not supposed to call the subscribe_attribute command?

I see that I get updates to an attribute that I subscribe to, but I don't see that I get events for other attributes.

**Comment by marcelveldt** [comment]
the server now defaults to a wildcard so as soon as you send the "start_listening" command, you will from then on receive all attribute updates and urgent events, no longer needed to explicitly tell what attributes to subscribe. You can do filtering in your own implementation.

**Comment by olavt** [comment]
Ok, sounds good as a starting point.

What about attributes for clusters like Software Diagnostics Cluster? Doesn't the device periodically updates attributes like  ThreadMetrics,  CurrentHeapFree etc.? Shouldn't I get events for these? I get updated values if I request them with the "read_attribute" command. I just need to understand why I get events for some and not for others.

**Comment by marcelveldt** [comment]
That is completely device dependent but I think you also want the non urgent device events.
I skipped those for now because they are verbose and cause a lot of traffic while we are already struggling with thread network stability.

Let's keep this open as feature request to add an additional/optional subscription to the non-urgent node events as well, maybe with a slow interval.

**Comment by olavt** [comment]
I'm not talking about events in general here, only attribute updates. Are you categorizing attributes into urgent / non-urgent ones? If I see that values have changed between calls to "read_attribute", I would have assumed that I should have received an "attribute_updated" in-between.

Ideally, I would have lefty more of the responsibility for managing this up to the caller and have a bit less stuff happen "automagically".

**Comment by marcelveldt** [comment]
You get ALL attribute updates already.

**Comment by olavt** [comment]
Ok, then I need to understand why I'm getting "attribute_updated" events for carbonmonoxideconcentrationmeasurement measured-value, but not for softwarediagnostics current-heap-free.

Both are changing values over time.

**Comment by marcelveldt** [comment]
I think that is device dependent. Are you sure the device should report that as attribute updated reports ?

**Comment by marcelveldt** [comment]
> According to the .zap file the attribute reporting are enabled for the softwarediagnostics attributes:

OK, then you should get them. If not, you have a device issue.
As I said, we're doing a wildcard sub to the device, all attributes updates are forwarded

**Comment by balloob** [comment]
@olavt make sure you run the latest Matter server version.

**Comment by marcelveldt** [comment]
The device decides what to send with a wildcard sub
