### ISSUE TITLE
Websocket not opened

### ISSUE THREAD

**Issue by AdarshVadlapatla** [home-assistant-libs/python-matter-server#637]
I am not able to send any messages because I cant establish  a websocket connection . I am running the python matter server  locally on a rasp pi with the command "sudo python3.11 -m matter_server.server --storage-path /data," as 3.11 was necessary and a storage path was as well as without the storage path and just running matter_server.server caused errors. This is also an issue as it should be able to run without a specified storage path. But incidentally even with all of that I cannot establish a connection to that websocket and no logging is useful. This is the terminal output and after vendor storage it freezes the log until i control c, During that time i tried sending numerous websockets but all failed to find connections.
<img width="1101" alt="Screenshot 2024-03-15 at 2 23 56 AM" src="https://github.com/home-assistant-libs/python-matter-server/assets/157755226/36c158b6-63c1-4736-bab6-21e15668add0">
I tried sending a message to ws://localhost:5080 thats what the matter dashboard says as I am running the matter server locally on a pi. Any fixes? For reference, I downloaded both the client and server and that automatically dowloaded the linux chip wheels. I do not have the entire matter sdk on the pi. I downloaded python 3.11 as that was necessary for none type errors.

**Comment by marcelveldt** [comment]
Are you a developer that is either contributing to this project or consuming the matter server in your own project ?

**Comment by ashritav2004** [comment]
I am doing both in a way, i am trying to develop for my own project and any advancements or additions that help I would love to add to contribute as a developer to the current repo. I have been bottlenecked by this error of not being able to access the server and actually run any websocket commands for a few days though.

**Comment by AdarshVadlapatla** [comment]
I am doing both in a way, i am trying to develop for my own project and any advancements or additions that help I would love to add to contribute as a developer to the current repo. I have been bottlenecked by this error of not being able to access the server and actually run any websocket commands for a few days though.

**Comment by marcelveldt** [comment]
The correct websocket address is ws://localhost:5080/ws
