### ISSUE TITLE
Device type in dignostic info.

### ISSUE THREAD

**Issue by Luligu** [home-assistant-libs/python-matter-server#696]
Hi,
I'm the author Matterbridge https://github.com/Luligu/matterbridge.

I would like to understand why in the diagnostic info the Device type is Unknown.
![Matterbridge aggregator](https://github.com/home-assistant-libs/python-matter-server/assets/132135057/c1c21bc2-8397-45c5-bafa-920ea86ff4c3)
Is this a Matterbridge issue or just an issue in your code ?
Matterbridge pairs with all controllers without problems.
Thanks in advance.
Luligu

**Comment by marcelveldt** [comment]
Most probably you forgot to implement one of the diagnostics clusters.
