### ISSUE TITLE
Can't access interface after local setup on MacOS + Docker

### ISSUE THREAD

**Issue by vnguyen42** [home-assistant-libs/python-matter-server#714]
I'm trying to get Python Matter Server to run in Docker on MacOS, the service start fine using the recommended docker-compose :

version: '3'
services:
  matter-server:
    container_name: matter-server
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    restart: unless-stopped
    security_opt:
      - apparmor=unconfined
    volumes:
      - ./data:/data
      - /run/dbus:/run/dbus:ro
    network_mode: host
    
However when trying to access http://localhost:5580/, nothing happens. Home Assistant can't connect to it via ws://localhost:5580/ws either.

The only way I'm able to successfully access the interface at localhost:5580 is by removing "network_mode: host" and adding ports:
       - "5580:5580" in the docker-compose file, but then Home Assistant still fail to connect using ws://localhost:5580/ws.
       
Any way I could troubleshoot this ?

**Comment by marcelveldt** [comment]
Docker on macos doesnt support network host mode.
Also, running the Matter server in docker is completely at your own risk, we do not provide support for it.

**Comment by bubez81** [comment]
you can try this option:
![Screenshot 2024-05-22 alle 06 12 24](https://github.com/home-assistant-libs/python-matter-server/assets/19486458/d378a688-135f-4de7-8e48-78c84258b8c5)
