### ISSUE TITLE
6.3.0: Bluetooth commissioning is not available

### ISSUE THREAD

**Issue by olavt** [home-assistant-libs/python-matter-server#808]
I tried to commission a Matter over Thread device using 6.3.0 and got this error:

Bluetooth commissioning is not available.

6.2.2 works fine.

**Comment by marcelveldt** [comment]
You need to assign a bluetooth adapter when starting the server. Not sure if we also expose that to docker

**Comment by olavt** [comment]
Can you explain a bit more on how this is working and why behavior changed?

**Comment by olavt** [comment]
Shouldn't the new releases default to the 6.2.2 behavior if the new Bluetooth capabilities are not used / specified and not fail?

**Comment by agners** [comment]
> Can you explain a bit more on how this is working and why behavior changed?

The behavior changed with #799.

To restore what the Server did before, just pass `--bluetooth-adapter 0` to the container.

> Shouldn't the new releases default to the 6.2.2 behavior if the new Bluetooth capabilities are not used / specified and not fail?

The problem is that, at least in the past, there were issues when Home Assistant and the Matter Server used the same adapter. So rather then default to adapter 0, currently Bluetooth is disabled so the user needs to make a conscious decision which adapter to use (and potentially disable on HA side).

**Comment by marcelveldt** [comment]
Can you actually pass that to the container or do we need to add a environmental variable ?

**Comment by olavt** [comment]
Passing --bluetooth-adapter 0 to the "docker run" command does not work.

It would be great if a feature could be added to support setting this option when running in a Docker container.

**Comment by agners** [comment]
I just checked, it works here. Make sure you pass the default command line (as in CMD of the Dockerfile) as well! So e.g.

```
    ...
    ghcr.io/home-assistant-libs/python-matter-server:stable --storage-path /data --paa-root-cert-dir /data/credentials --bluetooth-adapter 0
```

Also created a PR to clarify this in the readme, see #826.

**Comment by olavt** [comment]
Thanks! Adding the command options after the image name works!
