### ISSUE TITLE
pip dependency chain is broken

### ISSUE THREAD

**Issue by doubledgedboard** [home-assistant-libs/python-matter-server#836]
installing just `python-matter-server` installs only `home-assistant-chip-clusters` and fails to install `home-assistant-chip-core` resulting in a broken dependency chain

```
● matterserver.service - matterserver
     Loaded: loaded (/etc/systemd/system/matterserver.service; enabled; preset: enabled)
     Active: active (running) since Tue 2024-07-23 19:04:14 CDT; 327ms ago
   Main PID: 960 (python)
      Tasks: 1 (limit: 1093)
     Memory: 23.1M
        CPU: 320ms
     CGroup: /system.slice/matterserver.service
             └─960 /srv/homeassistant/bin/python -m matter_server.server

Jul 23 19:04:14 homeassistant python[960]:   File "<frozen runpy>", line 189, in _run_module_as_main
Jul 23 19:04:14 homeassistant python[960]:   File "<frozen runpy>", line 148, in _get_module_details
Jul 23 19:04:14 homeassistant python[960]:   File "<frozen runpy>", line 112, in _get_module_details
Jul 23 19:04:14 homeassistant python[960]:   File "/srv/homeassistant/lib/python3.12/site-packages/matter_server/server/__init__.py", line 3, in <module>
Jul 23 19:04:14 homeassistant python[960]:     from .server import MatterServer
Jul 23 19:04:14 homeassistant python[960]:   File "/srv/homeassistant/lib/python3.12/site-packages/matter_server/server/server.py", line 32, in <module>
Jul 23 19:04:14 homeassistant python[960]:     from ..server.client_handler import WebsocketClientHandler
Jul 23 19:04:14 homeassistant python[960]:   File "/srv/homeassistant/lib/python3.12/site-packages/matter_server/server/client_handler.py", line 13, in <module>
Jul 23 19:04:14 homeassistant python[960]:     from chip.exceptions import ChipStackError
Jul 23 19:04:14 homeassistant python[960]: ModuleNotFoundError: No module named 'chip.exceptions'
```

installing `home-assistant-chip-core` manually results in a version newer than the expected version from `home-assistant-chip-clusters`, also causing an error (see #835 )

and for posterity, the current upgrade procedure that works to workaround this issue, is:

```
pip uninstall python-matter-server
pip uninstall home-assistant-chip-clusters
pip uninstall home-assistant-chip-core
pip install python-matter-server
pip install home-assistant-chip-core==$CLUSTERS_VERSION
```

where `$CLUSTERS_VERSION` is the version of `home-assistant-chip-clusters` that got installed by `pip install python-matter-server`

**Comment by marcelveldt** [comment]
First of all, installing the server is done by 'pip install python-matter-server[server]'

Second of all;
The only officially supported way of running Matter Server is by running the Home Assistant add-on and secondly the standalone docker image (with al noted about networking and host patches)

Running a production setup with just installing the python packages is NOT supported.

**Comment by doubledgedboard** [comment]
I don't understand the defensive attitude for this open source project. I'm using it at home, I'm an experienced devops professional, and this is an open source project.

If you really don't want people using or contributing to this I will happily fork it and fix your issues myself.

**Comment by marcelveldt** [comment]
It's not supported and we have documented that as well. Next to that you ignored the fact that this issue tracker is not for user support and ignored that as well. Sorry we do not have the capacity to support every corner case setup, especially not with Matter where a lot of moving parts are involved, dependencies on host OS, kernel patches and so on. So you are free to tinker around but we don't provide support. It's not meant offensive but just a way of politely telling you ignored all our warnings what is supported and what not.
