### ISSUE TITLE
Generate Descriptions failing in dashboard script/setup

### ISSUE THREAD

**Issue by oidebrett** [home-assistant-libs/python-matter-server#854]
Issue: AttributeError: module 'chip.clusters.Objects' has no attribute 'PowerTopology' when running dashboard/script/setup

Library Versions:
python-matter-server: commit 5e441bb3d63e4c6f9f5e7d569adc1c146e14b918
home-assistant-chip-clusters 2024.7.1
home-assistant-chip-core     2024.7.1

Local Development Installed using:
`pip install -e ".[server]"`

Activated venv by:
`source .venv/bin/activate`

Possible cause of error:
The chip-core and chip-clusters wheels that are being used in the install of the python-matter-server are for an older version of the matter protocol and the latest device types and attributes that are expected are not present in these wheels.

Debugging:

When I print out the attributes in the Objects from the chip.clusters module that is imported in generate_descriptions.py I dont see the 
some of the latest device type definitions that are in the latest version of client/models/device_types.py 

`from chip.clusters import Objects as all_clusters
print(dir(all_clusters))`

`['AccessControl', 'AccountLogin', 'Actions', 'ActivatedCarbonFilterMonitoring', 'AdministratorCommissioning', 'AirQuality', 'ApplicationBasic', 'ApplicationLauncher', 'AudioOutput', 'BallastConfiguration', 'BarrierControl', 'BasicInformation', 'BinaryInputBasic', 'Binding', 'BooleanState', 'BridgedDeviceBasicInformation', 'CarbonDioxideConcentrationMeasurement', 'CarbonMonoxideConcentrationMeasurement', 'Channel', 'ChipUtility', 'Cluster', 'ClusterAttributeDescriptor', 'ClusterCommand', 'ClusterEvent', 'ClusterObject', 'ClusterObjectDescriptor', 'ClusterObjectFieldDescriptor', 'ColorControl', 'ContentLauncher', 'Descriptor', 'DiagnosticLogs', 'DishwasherAlarm', 'DishwasherMode', 'DoorLock', 'ElectricalMeasurement', 'EthernetNetworkDiagnostics', 'FanControl', 'FaultInjection', 'FixedLabel', 'FlowMeasurement', 'FormaldehydeConcentrationMeasurement', 'GeneralCommissioning', 'GeneralDiagnostics', 'GroupKeyManagement', 'Groups', 'HepaFilterMonitoring', 'IcdManagement', 'Identify', 'IlluminanceMeasurement', 'IntFlag', 'KeypadInput', 'LaundryWasherControls', 'LaundryWasherMode', 'LevelControl', 'LocalizationConfiguration', 'LowPower', 'MatterIntEnum', 'MediaInput', 'MediaPlayback', 'ModeSelect', 'NetworkCommissioning', 'NitrogenDioxideConcentrationMeasurement', 'NullValue', 'Nullable', 'OccupancySensing', 'OnOff', 'OnOffSwitchConfiguration', 'OperationalCredentials', 'OperationalState', 'OtaSoftwareUpdateProvider', 'OtaSoftwareUpdateRequestor', 'OzoneConcentrationMeasurement', 'Pm10ConcentrationMeasurement', 'Pm1ConcentrationMeasurement', 'Pm25ConcentrationMeasurement', 'PowerSource', 'PowerSourceConfiguration', 'PressureMeasurement', 'ProxyConfiguration', 'ProxyDiscovery', 'ProxyValid', 'PulseWidthModulation', 'PumpConfigurationAndControl', 'RadonConcentrationMeasurement', 'RefrigeratorAlarm', 'RefrigeratorAndTemperatureControlledCabinetMode', 'RelativeHumidityMeasurement', 'RvcCleanMode', 'RvcOperationalState', 'RvcRunMode', 'SampleMei', 'Scenes', 'SmokeCoAlarm', 'SoftwareDiagnostics', 'Switch', 'TargetNavigator', 'TemperatureControl', 'TemperatureMeasurement', 'Thermostat', 'ThermostatUserInterfaceConfiguration', 'ThreadNetworkDiagnostics', 'TimeFormatLocalization', 'TimeSynchronization', 'TotalVolatileOrganicCompoundsConcentrationMeasurement', 'UnitLocalization', 'UnitTesting', 'UserLabel', 'WakeOnLan', 'WiFiNetworkDiagnostics', 'WindowCovering', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'dataclass', 'field', 'float32', 'typing', 'uint']`

for example:
all_clusters.PowerTopology,
all_clusters.ElectricalEnergyMeasurement,
all_clusters.ElectricalPowerMeasurement,
are not present in the chip clusters

**Comment by marcelveldt** [comment]
Not sure what you are trying to accomplish here - just install the latest version with the latest sdk wheels

**Comment by oidebrett** [comment]
> Not sure what you are trying to accomplish here - just install the latest version with the latest sdk wheels

Hi, I am trying to install the matter server for development of a separate project and to help contribute to this repo. I tried to install the server's required sdk wheels using

`pip install -e ".[server]"`

I will try again with a later version of this repo and see if the problem still exists. Is there something else I need to do to get the latest sdk wheels?

**Comment by marcelveldt** [comment]
No, that should be sufficient, it will grab the version of the wheels currently pinned in the project and I know for a fact that those contain the 1.3 clusters like ElectricalEnergyMeasurement.

**Comment by oidebrett** [comment]
Closing. This was an error on my part with the installation.
