### ISSUE TITLE
Selecting interface on a QNAP using docker

### ISSUE THREAD

**Issue by juliodee** [home-assistant-libs/python-matter-server#866]
I am struggling to get a Nanoleaf Thread/Matter downlight connected to Home Assistant. My environment is QNAP / Docker / Portainer, network "host" mode (albeit I also tried configuring a macvlan environment). I have been on this for days so please know I have done my best to read and try everything I possibly can.

I respect docker environments are not supported, so please accept my apologies if incorrect to post this as an "issue".

I understand the ability to select network interface is not possible however I encounter the following issue:

When I try pairing the Nanoleaf between my thread border router and Home Assistant I receive a network unreachable error:
2024-09-02 06:18:23.744 (MainThread) INFO [matter_server.server.device_controller] Starting Matter commissioning with code using Node ID 160.
2024-09-02 06:18:23.829 (Dummy-2) CHIP_ERROR [chip.native.-] src/inet/UDPEndPointImplSockets.cpp:416: OS Error 0x02000065: Network is unreachable at src/controller/SetUpCodePairer.cpp:280
2024-09-02 06:18:53.752 (Dummy-2) CHIP_ERROR [chip.native.CTL] Discovery timed out
2024-09-02 06:18:53.753 (Dummy-2) CHIP_ERROR [chip.native.ZCL] Secure Pairing Failed
2024-09-02 06:18:53.753 (Dummy-2) WARNING [chip.ChipDeviceCtrl] Failed to establish secure session to device: src/controller/python/ChipDeviceController-ScriptDevicePairingDelegate.cpp:89: CHIP Error 0x00000003: Incorrect state
2024-09-02 06:18:53.754 (MainThread) ERROR [matter_server.server.client_handler] [140161301871824] Error while handling: commission_with_code: Commission with code failed for node 160.

I found that:
Home Assistant auto picks up "br0" as my adapter and includes the following details in it's "Settings / System / Network Adapter" section:
Auto Configure
Detected: br0 (192.168.69.100/24, fd4c:bc92:95ff:f995:208:####:####:####/64, fe80::208:9bff:fef9:c142/64) 
(I changed to # for privacy - not sure if required, I am still getting my head around public / private ipv6)

However, Python Matter Server selects Eth1 as its interface (per the log output):
[1725259889.292270][1:1] CHIP:DL: Got Ethernet interface: eth1
[1725259889.293322][1:1] CHIP:DL: Found the primary Ethernet interface:eth1
[1725259889.294918][1:1] CHIP:DL: Failed to get WiFi interface
[1725259889.294997][1:1] CHIP:DL: Failed to reset WiFi statistic counts

In one of my tests, I configured a macvlan and noted Python Matter Server then auto selected br0 as the adapter (there was only 2 interfaces created under this scenario), and whilst I still can't get the device to connect to HA due to different error messages, the ipv6 network was at least "reachable". Noting PMS should be configured in "host" mode, I'd really like to get PMS running in Host mode rather than a macvlan to move forward with my testing / getting things working.

Here is the output from an "ifconfig" within my Python Matter Server container:
br0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.69.100  netmask 255.255.255.0  broadcast 192.168.69.255
        inet6 fe80::208:9bff:fef9:c142  prefixlen 64  scopeid 0x20<link>
        inet6 fd4c:bc92:95ff:f995:208:####:####:####  prefixlen 64  scopeid 0x0<global>
        ether 00:08:9b:##:##:##  txqueuelen 1000  (Ethernet)
        RX packets 20123404  bytes 19471485859 (18.1 GiB)
        RX errors 0  dropped 155  overruns 0  frame 0
        TX packets 18476648  bytes 8421258436 (7.8 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

docker0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.5.1  netmask 255.255.255.0  broadcast 10.0.5.255
        ether 86:97:68:##:##:##  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 29708  bytes 3576033 (3.4 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        ether 00:08:9b:##:##:##  txqueuelen 1000  (Ethernet)
        RX packets 24396965  bytes 20926378363 (19.4 GiB)
        RX errors 0  dropped 17914  overruns 0  frame 0
        TX packets 20462866  bytes 8476309848 (7.8 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device memory 0x81800000-8187ffff  

eth1: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether 00:08:9b:##:##:##  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device memory 0x81900000-8197ffff  

eth2: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether 00:08:9b:##:##:## txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device memory 0x81600000-8167ffff  

eth3: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether 00:08:9b:##:##:##  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device memory 0x81700000-8177ffff  

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 2232852  bytes 575068248 (548.4 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2232852  bytes 575068248 (548.4 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lxcbr0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.3.1  netmask 255.255.255.0  broadcast 10.0.3.255
        ether b2:45:3f:##:##:##  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 29797  bytes 3580775 (3.4 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

Unfortunately I don't know if/how to 'turn off' all other interfaces in QNAP when in "host" mode, forcing Python Matter Server to be limited to br0.

I can't remember the topic but I recall seeing one that noted the ability to select adapter was not possible and there has been talk about its feasibility. Hoping someone that can assist with any way of getting Python Matter Server to at least use the same adapter that Home Assistant uses.

**Comment by marcelveldt** [comment]
Docker environments are not supported, especially not for Thread devices. Your host OS lacks all the required kernel features and patches to make this work. The only thing you could perhaps try is a bridge/macvlan network for the matter server docker container onto your network.

I'm going to close this issue now here because we do not provide support for docker environments (for good reasons) but maybe you can join our discord server (matter and thread channels) to see if we can help you together with the community ?
