### ISSUE TITLE
Aqara e1 Switch

### ISSUE THREAD

**Issue by galzil** [home-assistant-libs/python-matter-server#937]
Home Assistant Core 2024.5.5 
Python Matter Server 2024.9.0
On containers using CasaOS

I've added both Aqara m1s and G3 hubs through matter integration,
I can see all the devices but the e1 switch.

I'll appreciate any help

**Comment by marcelveldt** [comment]
Please use the Home Assistant issue tracker to get support (or discord, or the forums).
The issue tracker here is NOT for user support (as it also clearly states when you try to create a report).
Thanks
