### ISSUE TITLE
'DNSSD packet parsing failed' logging

### ISSUE THREAD

**Issue by nanhoes** [home-assistant-libs/python-matter-server#960]
Any way to minimize the logging on this? There are about 30 log entries per second resulting in about 1GB worth of log file data per day. Any help would be appreciated, thanks!

**Comment by marcelveldt** [comment]
Do you have some sort of mdns forwarder on your network ?
The Unifi mdns repeater is known to cause massive issues with mdns. Also there is some add-on that bridges chromecast to airplay, which is also doing bad stuff with mdns.
