### ISSUE TITLE
Command in double

### ISSUE THREAD

**Issue by Cyril-E** [home-assistant-libs/python-matter-server#97]
Hello

The Matter Plug in find my Philips Hue Bridge (they have the Matter Beta)
For all Lights the command are in double usable but they have for (see the picture)
And juste for the esthetique, they have no icon

![Capture d’écran 2022-11-26 à 08 28 46](https://user-images.githubusercontent.com/627667/204077601-38f15362-ae7f-46c9-86c2-4951bed0d004.png)
![Capture d’écran 2022-11-26 à 08 31 58](https://user-images.githubusercontent.com/627667/204077658-7c322807-9197-4141-92b8-11ee51557f66.png)

**Comment by marcelveldt** [comment]
Matter bridge device support is not yet ready. Please use an already supported device type to try out Matter.
I expect/hope to work out the latest issues with bridges for next HA release.
