### ISSUE TITLE
Unraid documentation said to use Host mode with ipv6, but that's not possible

### ISSUE THREAD

**Issue by jtowe1** [home-assistant-libs/python-matter-server#992]
When installing the matter-server in Unraid the template says

```
REQUIREMENTS:
Unraid needs to have IPV4+6 enabled on the network interface! Make sure your you run the container 
on the host network. The host network interface needs to be in the same network as 
the Android/iPhone device you are using for commissioning. Matter uses link-local multicast 
protocols which do not work accross different LANs or VLANs.
```

But I don't believe `host` network can use ipv6.  How is this container supposed to be configured in unraid?

**Comment by marcelveldt** [comment]
1) No user support here
2) Running Matter server in docker is not officially supported (its completely at your own risk).

My best tip would be to ask these questions on the forums or discord to see if somebody has it working.
